### ISSUE TITLE
renaming files doesn't work

### ISSUE THREAD

**Issue by ronp001** [ds300/patch-package#107]
https://github.com/ds300/patch-package/blob/8844aee01377c4c96c886133c4fab70dcdb88b76/src/patch/parse.ts#L170

should be:
```js
const toPath = this.lines[++this.i].slice("rename to ".length).trim()
```

**Comment by ds300** [comment]
Hi! :wave: Thanks for the report!

Nice catch! I literally just [discovered this bug last night](https://github.com/ds300/patch-package/commit/293ab6aaab52d0335fd031de8bf9e5a30685afb4) too and happened to publish a fix for it a few minutes ago: `patch-package@6.0.0-14`

So I'll close this. Thanks again, it's super cool that you debugged thee issue :heart:
