### ISSUE TITLE
Opens merge

### ISSUE THREAD

**Issue by GantMan** [ds300/patch-package#109]
From the directions, it's supposed to generate the patch, not open my merge application.

Help?
![brain](https://user-images.githubusercontent.com/997157/51430889-d31f9080-1be6-11e9-89df-543e782ecd5c.gif)

**Comment by GantMan** [comment]
My guess is that it's supposed to generate the patch with no UI popping up.  But no clue *shrug*

**Comment by GantMan** [comment]
It's something in my `~/.gitconfig` I hollowed it out and made the patch, then put all my settings back in.
It worked that time.   Maybe a warning in Readme?  I'm a bit outside of my depth in Git *shrug*

**Comment by ds300** [comment]
Hmm weird. Can you share your .gitconfig?

**Comment by ds300** [comment]
I think it's probably the diff tool. I wonder if I can force git to not open people's custom diff tools 🤔
