### ISSUE TITLE
local git color config breaks applying the patch

### ISSUE THREAD

**Issue by panva** [ds300/patch-package#115]
I assume the package uses the system available git to generate the patch file. 

Problem is local git can be configured with colors enabled which then are a part of the captured git command output.

Having the colours in the patch file breaks applying the patch during postinstall

**Comment by ds300** [comment]
Hi! 👋Thanks for raising this! Other people have had similar issues and I've been looking at figuring out how to ignore git's global config. Will let you know when I have a solution.

**Comment by ds300** [comment]
I fixed this and just published 6.0.0 :tada:

**Comment by panva** [comment]
Thank you.
