### ISSUE TITLE
is it normal that the patch is huge ?

### ISSUE THREAD

**Issue by vesper8** [ds300/patch-package#117]
I just used this for the first time. 
I cloned a copy of  https://github.com/vuex-orm/plugin-axios
applied the changes from this PR: https://github.com/vuex-orm/plugin-axios/pull/8

and then created a patch

It works wonderfully well, however the patch it created is 80mb in size!! It's huge.. specially considering I need to commit it to the repository. It's like 20x bigger than the size of the rest of the committed code

Is this normal? Is there no way around this?

Thanks!

**Comment by ds300** [comment]
Hi! :wave:

:eyes: no that's not normal. Can you provide a more detailed description of how you modified the contents of your `node_modules/@vuex-orm/plugin-axios` folder?

**Comment by ds300** [comment]
Also note that you can be more targeted when making a patch, see the readme section on `--include` and `--exclude`

**Comment by vesper8** [comment]
Sure thing! I hope this explanation can help me understand how to create a small patch and what I might have done wrong.

To create the above patch I installed the package normally

```
    "@vuex-orm/core": "^0.31.2",
    "@vuex-orm/plugin-axios": "^0.2.2",
```

Then I cloned the fork from another author which includes the PR I wanted to apply:

https://github.com/Akhail/plugin-axios.git

From that folder I grabbed the src folder and package.json file and copied it over to the installed package inside cd node_modules/@vuex-orm/plugin-axios

Since this "PR" includes modifications to the package.json, I then cd'd inside the folder cd node_modules/@vuex-orm/plugin-axios, and ran yarn, followed by yarn build

I then cd'd back the root of my project and ran

```
yarn patch-package @vuex-orm/plugin-axios
```

and that created the 78mb patch file, which works as intended aside from being huge

hope that helps!

**Comment by ds300** [comment]
Ah, that's not a good way to do it!

You're probably adding a bunch of source files and node_modules and build artefacts into the patch file!

You should delete the patch file, run yarn/npm, copy the dist/index.js from that PR into the one in your node_modules then run patch-package again.

**Comment by ds300** [comment]
thanks for the idea! Maybe I'll do that if other people have similar issues. For now it doesn't seem to be a common problem.

Cheers!
