### ISSUE TITLE
Recommended practice - partching "src" or "dist" ?

### ISSUE THREAD

**Issue by tmcdos** [ds300/patch-package#12]
I am using **patch-package** on a Vue-CLI project which (obviously) depends on Vue and Vue-router. I want to patch both dependencies but wonder what is the best practice for doing it. I mean - packages contain both **src** and **dist** folder. If I modify file(s) in **src** folder - this does not lead to automatic rebuild of files in **dist** folder of the package. Am I supposed to only patch files in the **dist** folder ? Or should I patch files in **src** and then manually rebuild the patched packages ? **dist** folder contains different variants of the package (like `vue.common.js`, `vue.esm.js`, `vue.runtime.common.js`, `vue.runtime.min.js` ...) which are build from the same **src** files.
Either way has a disadvantage:

- patching only files in **dist** folder potentially requires applying the same patch over several files
- patching only files in **src** folder requires manual build (and multiple 100+ Mb luggage of **./node_modules** for each patched package)

How do you do it ?

**Comment by ds300** [comment]
I haven't been in the same situation yet, but I would probably do the following:

- make the desired changes in src
- rebuild the dist folder manually once
- run patch-package to generate the patch file which contains changes for both the src and dist folders

Does that solve your problem?

**Comment by tmcdos** [comment]
Well, I did manually edit the files in both SRC and DIST and skipped the building step - currently it works, I shall see what happens when some day I upgrade the packages ...

**Comment by ds300** [comment]
I'm going to close this issue since the question appears to be resolved. If you have any further questions about this topic, or you feel that the question is still unanswered, please feel free to re-open the issue!
