### ISSUE TITLE
Don't install `@types/is-ci` as a dependency

### ISSUE THREAD

**Issue by ngyikp** [ds300/patch-package#121]
I'm not using TypeScript for my project so installing types for an unrelated package seems superfluous

https://github.com/ds300/patch-package/commit/d1f24a9efc82d39620430cb5ab0723b11b5d372a#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R67

**Comment by ds300** [comment]
Hi! :wave: Thanks for the report! I'll fix this for the next release.
