### ISSUE TITLE
TypeError: Cannot read property 'foo' of undefined

### ISSUE THREAD

**Issue by mrozekma** [ds300/patch-package#123]
If a package only has a `dependencies` or `devDependencies` section, but not both, [this code](https://github.com/ds300/patch-package/blob/f8152534824bf1ed77fc15ab0bb55a30903d99e7/src/makePatch.ts#L65-L67) will error out with:

> TypeError: Cannot read property 'foo' of undefined

**Comment by ds300** [comment]
Hi! :wave: Thanks for the report! I'll fix this soon.

**Comment by rvillalba-novetta** [comment]
I seem to be getting the same error (Cannot read property 'react-dev-utils' of undefined) when I try "npx patch-package react-dev-utils"  from within my CRA project.

**Comment by filoxo** [comment]
FWIW I encounted this and found that it was because I was trying to patch a package that had been installed with yarn (unintentionally) and so was missing from the package-lock.json file. Updating the package-lock.json file was the fix.
