### ISSUE TITLE
Problems building packages

### ISSUE THREAD

**Issue by elie222** [ds300/patch-package#127]
I've had trouble using patch-package on a lot of projects.

Not all npm packages will publish all the files needed to build from scratch.

If a project only publishes an uglified dist folder to npm, is there a way to effectively use `patch-package` with it?

I've run into an issue where the `src` folder has been published to npm, but some config files have not been published so it's not easy to do the build step. Do I just have to copy over the missing files from GitHub to do the build or am I missing something with how this package should be used?

This is a related issue that assumes you edit the `src` folder and then build again:
https://github.com/ds300/patch-package/issues/12

The issues I've run into here seem to happen with every package I try and edit, so I'm not sure if I'm misunderstanding how patch-package should be used, or it's just extremely limited as to when it can be used.

**Comment by elie222** [comment]
The package I'm trying to patch right now is:
https://github.com/jpuri/react-draft-wysiwyg

But it's config files are put in the npmignore file so the build doesn't work:
https://github.com/jpuri/react-draft-wysiwyg/blob/master/.npmignore

**Comment by avrahamcool** [comment]
Sounds like you should create an issue there, asking to add the relevant files into the npm package.

What you are discribibg here is inconvenient, but there nothing you can do from patch-package side if the package is missing some key files.

**Comment by ds300** [comment]
> If a project only publishes an uglified dist folder to npm, is there a way to effectively use `patch-package` with it?

Not really, sorry. The best you can do clone the repo normally, build a new version of the uglified file yourself, then copy it into your node_modules in the correct place, then run patch-package. But it will probably be an unreadable patch file. Might as well just fork the repo in those situations.

> The issues I've run into here seem to happen with every package I try and edit, so I'm not sure if I'm misunderstanding how patch-package should be used, or it's just extremely limited as to when it can be used.

That surprises me. I can only think of one package that loads a minified bundle at dev time. Every single package I've tried to patch has been a good npm citizen in that regard. Sorry to hear your experience has been different 😕

**Comment by elie222** [comment]
No problem. Good to know. Thanks for a great package.

This is another package I tried editing with `patch-package` and ran into the same issues. It only publishes the `dist`:

https://github.com/mohsinulhaq/react-popper-tooltip/blob/master/package.json#L14-L16

What is considered best practice however? Is there any reason for this package to publish all files to npm? If yes, I can make a PR to edit that package and have it work nicer with `patch-package` in the future. But if working with `patch-package` is the only reason they likely won't accept the PR.

**Comment by ds300** [comment]
> What is considered best practice however? Is there any reason for this package to publish all files to npm?

Yeah what they've done is considered best practice. There's normally no reason to publish typescript source files to npm. I can see why you'd want to be able to patch the TS files and then compile the package during postinstall, but that would add a lot of overhead to every yarn/npm install. It's normally easy enough to patch the compiled JS directly in my experience.

**Comment by ds300** [comment]
Hope you don't mind if I close this issue. Glad to answer further questions, but this isn't an actionable item so I'd prefer to tidy up. Thanks!

**Comment by borekb** [comment]
> I can see why you'd want to be able to patch the TS files and then compile the package during postinstall, but that would add a lot of overhead to every yarn/npm install. It's normally easy enough to patch the compiled JS directly in my experience.

This could almost be in the README 😄.
