### ISSUE TITLE
"There don't appear to be any changes" even though there are

### ISSUE THREAD

**Issue by baobabKoodaa** [ds300/patch-package#128]
This is my first time trying to use patch-package. I followed the instructions, but it doesn't recognize my changes. What am I doing wrong? More details below.

1. I added `"postinstall": "patch-package"` inside `scripts` inside my project's `package-json`.
2. I ran `npm i patch-package`
3. I modified the package that I had problems with. In particular, I modified this file: `node_modules/react-simple-infinite-scroll/package.json`.
4. I ran `npx patch-package infinite-scroll`

I'm seeing this:

```
• Creating temporary folder
• Installing react-simple-infinite-scroll@0.0.1 with npm
• Diffing your files with clean files
⁉️  Not creating patch file for package 'react-simple-infinite-scroll'
⁉️  There don't appear to be any changes.
```

I'm guessing patch-package doesn't support me modifying `package.json` inside a node module?

**Comment by ds300** [comment]
Package.json files are ignored by default because npm adds absolute paths into them when installing packages so it creates noise. See https://github.com/ds300/patch-package/blob/master/README.md#options for how to configure what to ignore.

**Comment by baobabKoodaa** [comment]
Okay, thank you for the answer. I ended up using a different way to patch.

**Comment by MariusCatanoiu** [comment]
> Okay, thank you for the answer. I ended up using a different way to patch.

What way? :D

**Comment by baobabKoodaa** [comment]
I forked the project and released the patched fork on npm.

**Comment by dmatora** [comment]
I am having same issue getting ("There don't appear to be any changes") with trying to patch `node_modules/@pooltogether/hooks/node_modules/@pooltogether/bnc-onboard/dist/esm/connect-5e218485.js` which technically is not part of the repo
I've created patch manually but when I try to apply it I'm getting an error

**Comment by mitchmeyer1** [comment]
any answers? having the same issue on a .ts file!

**Comment by reyraa** [comment]
Had the same issue when fixing an issue with `msw`.
I created a test local repo, added the `package.json` file of `msw` to the test repo and committed. Then applied the changes I needed and ran `git diff`.
Now all I had to do was fixing the paths.

I had
```
diff --git a/package.json b/package.json
index 78e36be..df071bb 100644
--- a/package.json
+++ b/package.json
```

which I changed to 

```
diff --git a/node_modules/msw/package.json b/node_modules/msw/package.json
index 78e36be..df071bb 100644
--- a/node_modules/msw/package.json
+++ b/node_modules/msw/package.json
```
Worked like a charm.

**Comment by YewoMhango** [comment]
@ds300 I tried using `npx patch-package @smooth-dnd/react --include package\\.json$` (since I had modified the package.json file of @smooth-dnd/react) as you suggested, but it was still showing no changes. Or was I doing something wrong here?

Regardless, I applied the method suggested by @reyraa and that worked for me

**Comment by semiaddict** [comment]
> I also have this problem, I tried ` --include package\\.json$` but it doesn't work

This seems to work: `npx patch-package package-name --exclude` (see https://github.com/ds300/patch-package/issues/142#issuecomment-661067320)

**Comment by YG1ee** [comment]
@semiaddict Thanks for the solution. It totally worked for me!

**Comment by bertyhell** [comment]
I used this, if you only have changes in package.json, and you still want to ignore package-lock.json:
```
npx patch-package package-name --exclude "" --include package.json
```

**Comment by stevenqzhang** [comment]
@bertyhell your solution didn't work for me for some reason but @semiaddict 's did
