### ISSUE TITLE
Patchfile contain 250kb of sourcecode even if I've only changed a few files

### ISSUE THREAD

**Issue by xstable** [ds300/patch-package#129]
I only changed a few lines of code inside of react-native-video-player Package.
If I create the patch-file, it contains round about 250kb Code inside.

I've tried this with another component, same result: much to big patchfile.

The only special thing I found for those both components is, that I doesn't use the default import of the main-repository, but one special url: 

> "dependencies": {
> ....
>     "react-native-video": "tranvinhtruong/react-native-video",
>     "react-native-video-player": "ShariqMush/react-native-fullscreenvideo-player",
> ...
> }

If I look inside the patchfile of react-native-video-player+0.8.0.patch the huge ammount of unnecessary sourcecode is caused of the "/example" Directory. Even the yarn.lock-File of this example-Directory if fully put into the patchfile.

**BTW:** I've fully removed node_modules, did `yarn install` and run patch-package on this fresh installation. This also creates a patchfile with a size of 250kb, _even if I've didn't change anything._

Why does this happend. On which base does the patch-package compare what to put into the fetch-file?

**Comment by ds300** [comment]
This could be related to an edge case that I'm trying to solve already where patch-package could install the wrong version of the package when making a patch file.

Another possibility in your case is that xcode is modifying some files under the hood.

Either way, you might be able to get around the problem by using the `--include` and/or `--exclude` cli options to specify which files to diff. https://github.com/ds300/patch-package#options

**Comment by ds300** [comment]
I just published a fix for the edge case I mentioned. It's in 6.0.5. Let me know whether that solves you problem!

**Comment by ds300** [comment]
I'm going to close this issue due to inactivity. Please feel free to open a new one if you're still having trouble!
