### ISSUE TITLE
Error when installing or upgrading another package

### ISSUE THREAD

**Issue by Alex-Mann** [ds300/patch-package#13]
I get this error when I install or upgrade another package: 
```
Exit code: 1
Command: sh
Arguments: -c ln -s lib/{ios,android} .
Directory: /Users/alexandermann/Code/Whisk/whisk-mobile-client/node_modules/react-native-interactable
Output:
ln: ./ios: File exists
ln: ./android: File exists
```
I am using zsh as my default shell and am assuming it has something to do with that?

**Comment by ds300** [comment]
Thanks for the report! Unfortunately, I don't understand what steps you took to get that output. Can you describe how to reproduce the issue in more detail?

**Comment by Alex-Mann** [comment]
It happens after I `yarn add` a package... Not sure really what the root cause is since the error message is very undescriptive.

**Comment by ds300** [comment]
does it happen if you run `yarn patch-package`?

**Comment by ds300** [comment]
Hi @Alex-Mann, any update on this issue? I'd like to help find the problem, and I'd still need some more information about when it happens. A repository that reproduces the issue would be the best thing.

**Comment by ds300** [comment]
I'm closing this issue for now, due to lack of activity. Please open it again if the problem persists and you can provide more details.
