### ISSUE TITLE
Patches not applied when using Heroku's Node buildpack

### ISSUE THREAD

**Issue by OliverJAsh** [ds300/patch-package#130]
This isn't an issue with `patch-package` specifically, but I wanted to share it here nonetheless to help anyone else who might run into this.

When using Heroku's Node buildpack, by default the following will happen during the build and startup process:

1. install all dependencies (including `devDependencies`) with `yarn --production="false"`
2. run build step
3. prune dev dependencies with `yarn --production="true"`
4. run the app

However, at step 3 when the dev dependencies are pruned, the [buildpack also specifies the `--ignore-scripts` flag when calling `yarn`](https://github.com/heroku/heroku-buildpack-nodejs/blob/v139/lib/dependencies.sh#L193) (since v119). This means `patch-package` will not run, because the `postinstall`/`prepare` scripts will not be ran. In turn, this means when the app runs, Node modules will not be patched (!).

The only workaround I'm aware of at the moment is to [disable pruning of dev dependencies with `YARN_PRODUCTION=false`](https://devcenter.heroku.com/articles/nodejs-support#package-installation).

I can semi-understand why the buildpack would want to avoid invoking scripts, since the scripts were already run after step 1. In any case I've raised an issue with the buildpack to investigate what changes we can make there: https://github.com/heroku/heroku-buildpack-nodejs/issues/634

**Comment by OliverJAsh** [comment]
Immediately closing this as it's not a bug with `patch-package`, but hopefully this will be helpful to others. @ds300 If you have ideas for alternative workarounds or fixes, I'd love to hear them!

**Comment by OliverJAsh** [comment]
I just ran into this again when setting up `patch-package` on a fresh Heroku application. Perhaps we should add a note to the docs for Heroku users: https://github.com/ds300/patch-package/pull/209

**Comment by naiyt** [comment]
Looks like with the latest version of the Heroku nodejs build script, you can accomplish this by using the `heroku-postbuild` step. That allows `patch-package` to work without losing the dev dependency pruning 🎉 .

Here's what my `package.json` scripts look like now:

```
  "scripts": {
    "postinstall": "patch-package",
    "heroku-postbuild": "patch-package"
  }
```

**Comment by neokim** [comment]
`heroku-postbuild` didn't work for me. Looks like during pruning dev dependencies which runs after `heroku-postbuild`, `yarn` restores the original version of packages. So I had to use `heroku-cleanup` instead which runs _after_ pruning.

Actually, [Heroku document](https://devcenter.heroku.com/articles/nodejs-support#heroku-specific-build-steps) says it runs after dependency caching, but it works for me anyway.

**Comment by esbanarango** [comment]
@neokim suggestion to use `heroku-cleanup` instead of `heroku-postbuild` worked for us. 🤝

**Comment by AlexanderPershin** [comment]
I added `"heroku-cleanup": "npx patch-package"` to my package.json for Strapi app
and output shows
```
remote: -----> Cleanup
remote:        Running heroku-cleanup
remote:        
remote:        > my-project@0.1.0 heroku-cleanup
remote:        > npx patch-package
remote:        
remote:        patch-package 6.4.7
remote:        Applying patches...
remote:        @strapi/admin@4.1.12 ✔
```
But no changes applyed. What am I doing wrong?

**Comment by Previesam** [comment]
@AlexanderPershin It worked for me I am also using strapi.

So i added `"postinstall": "npx patch-package"`, `"heroku-postbuild": "npx patch-package"`, `"heroku-cleanup": "npx patch-package"` but looking at the logs only heroku cleanup should do the trick.

**Comment by PaulBratslavsky** [comment]
Has anyone had this issue on digital ocean?

**Comment by IceBreaker8** [comment]
@Previesam @AlexanderPershin For strapi staging, I added:
"postinstall": "npx patch-package",
For prod, I also added:
"heroku-cleanup": "npx patch-package"

**Comment by benjie** [comment]
The solution is to add the `heroku-cleanup` script to your "scripts" in `package.json`; the reason being that the Heroku cleanup clears out the devDependencies, which triggers another call to your package manager, ignoring scripts, and thus `patch-package` is not called again. This causes issues for `yarn` at least.

```json5
{
  // ...
  "scripts": {
    "heroku-cleanup": "npx patch-package",
    // ...
```

Thanks to @IceBreaker8 above for the solve.
