### ISSUE TITLE
Trying to apply the patch fails because of "Error: Mode change is not required"

### ISSUE THREAD

**Issue by lomegg** [ds300/patch-package#135]
Just trying out the package for the first time. It failed to apply, so I dug in with some console logging and found out that patch-package was crashing because of the "Error: Mode change is not required". 

```
old mode 100644
new mode 100755
```
This chunk was added automatically by npx when I created the patch, as well as some other garbage. While I believe it is worthy to remove the junk from patches, I was not aware I had to do that. I suggest this error to be changed to a warning.

**Comment by ds300** [comment]
Hi! :wave: Thanks for the report!

You might be right that this should be a warning rather than a error. I'm intrigued by how you achieved that result though! Can you provide the steps to reproduce it?

**Comment by lomegg** [comment]
I literally just created a patch with `npx patch-package` command and it failed to apply on npm post-install. Unfortunately I don't have the original patch anymore but I recreated it a few times and error was pretty consistent.

**Comment by ds300** [comment]
Cool thank. Which package were you trying to patch? And which files did you modify? Was it in an npm project or a yarn project?

**Comment by ds300** [comment]
Downgraded this to a warning in v6.1.0
