### ISSUE TITLE
Trying to apply existing patch after cloning repository

### ISSUE THREAD

**Issue by elefantelimpio** [ds300/patch-package#136]
I have a patch crated from a pull request to a npm called node-restful. 

Well, each time I clone the repository, when I try to apply patch using npx patch-package it throws me an error:

D:\Projects\7sense_restful_api>npx patch-package
patch-package 6.0.2
Applying patches...

**ERROR** Failed to apply patch for package node-restful at path

    node_modules\node-restful

  This error was caused because patch-package cannot apply the following patch file:

    patches/node-restful+0.2.6.patch

  Try removing node_modules and trying again. If that doesn't work, maybe there was
  an accidental change made to the patch file? Try recreating it by manually
  editing the appropriate files and running:

    patch-package node-restful

  If that doesn't work, then it's a bug in patch-package, so please submit a bug
  report. Thanks!

    https://github.com/ds300/patch-package/issues

I tried to delete and create the patch again and it works
[node-restful+0.2.6REPOSITORY.patch.txt](https://github.com/ds300/patch-package/files/3012828/node-restful%2B0.2.6REPOSITORY.patch.txt)
[REGENERATEDnode-restful+0.2.6.patch.txt](https://github.com/ds300/patch-package/files/3012832/REGENERATEDnode-restful%2B0.2.6.patch.txt)

 but I dont know why because the file is the same as the file I cloned from repository

**Comment by ds300** [comment]
Hi! :wave: The version of patch-package you're using suffered from a bug which affected parsing patch files on windows. It was fixed in v6.0.4 so you just need to upgrade `patch-package` and you should be good to go :+1:

Let me know if that fixes your issue!

**Comment by elefantelimpio** [comment]
Nice, I'll try tomorrow again when I arrive to my job because there is the computer that I cloned this morning the repository .

**Comment by elefantelimpio** [comment]
Yes, upgrading patch-package to v6.0.4 solved my problem. Thanks you so much!
