### ISSUE TITLE
Support for new Node.js integrity policies

### ISSUE THREAD

**Issue by DanielRuf** [ds300/patch-package#137]
We should add a new flag to support the new integrity policy.

See https://snyk.io/blog/introducing-experimental-integrity-policies-to-node-js/

The flag should trigger a (re)creation / update of the policy file eg when we apply / generate patches.

**Comment by ds300** [comment]
Woah, thanks for raising this! Will be interesting to see how the feature develops. For now it looks very experimental and I don't think any action is required in patch-package. If you have ideas for how to support it, please detail them here! 🙏
