### ISSUE TITLE
Exit code should not be zero if there is an error applying patches

### ISSUE THREAD

**Issue by Livven** [ds300/patch-package#143]
Thoughts? Seems kinda dangerous e.g. if a package is updated and a patch fails to apply, but if you don't pay attention to the CLI output you will never know.

**Comment by ds300** [comment]
Hi! The exit code is 1 on CI but 0 at dev time to work around some odd behaviour of yarn's. see #86

**Comment by Livven** [comment]
Oh that's cool then. Might still be useful to have an option to force the non-zero exit code but this is fine by me 👍
