### ISSUE TITLE
Red "No patch files found" when there are no patches

### ISSUE THREAD

**Issue by borekb** [ds300/patch-package#145]
We removed the last necessary patch from our project but kept the `"postinstall": "patch-package"` npm script. This generates the following output:

<img width="315" alt="Screenshot 2019-06-10 at 16 57 11" src="https://user-images.githubusercontent.com/101152/59204390-cfde6e80-8ba0-11e9-98df-4b86323c9c29.png">

So it's exit code `0` (good) but a red color. Maybe it could be not-red? :)

Probably related: #51

**Comment by ds300** [comment]
Hmm yeah I could make it blue so it stands out but doesn't necessarily mean something is wrong 🤔 Good suggestion, thanks! :heart:

**Comment by borekb** [comment]
Or maybe a CLI flag, I'm not sure. But I understand that this is a tricky decision (on one hand, you want to highlight incorrect usage, on the other hand, sometimes, the lack of patch files is perfectly fine).

**Comment by ds300** [comment]
This was changed to blue in #211, gonna close this issue 🙏🏼
