### ISSUE TITLE
A single patch is failing on CI, but is working locally

### ISSUE THREAD

**Issue by me4502** [ds300/patch-package#147]
Hi,

A patch on CI (Jenkins Ubuntu image) is failing, however it is working for me locally on macOS Mojave.

Here's the patch, it's for react-share@3.0.0 https://gist.github.com/me4502/fcbbfeb90072b2322a08453aa17d8247

It's intended to just apply a PR (https://github.com/nygardk/react-share/pull/224/files) to it until the PR is merged.

Using:
Node 11.15.0
Yarn: 1.16.0

**Comment by ds300** [comment]
Hi 👋 thanks for the report! I'll look into this ASAP.

Apologies for the delayed response, I've been on holiday.

**Comment by nicolas-amabile** [comment]
Hi! Are there any updates on this? I'm getting a similar error using Codeship. It also works fine locally.

<img width="1337" alt="Screen Shot 2019-11-21 at 14 34 38" src="https://user-images.githubusercontent.com/8633440/69361870-19f96f00-0c6c-11ea-99e8-417228ca8b90.png">

**Comment by ds300** [comment]
I'm gonna close this due to inactivity. If anyone is still having problems with Codeship feel free to open another issue.
