### ISSUE TITLE
Patch failing to apply

### ISSUE THREAD

**Issue by dccarmo** [ds300/patch-package#149]
I created a patch for a Java file on a React Native dependency we're using in a project, but when applying the patch, I get this:

```
patch-package 6.1.2
Applying patches...

**ERROR** Failed to apply patch for package urbanairship-react-native at path
  
    node_modules/urbanairship-react-native

  This error was caused because patch-package cannot apply the following patch file:

    patches/urbanairship-react-native+2.2.1.patch

  Try removing node_modules and trying again. If that doesn't work, maybe there was
  an accidental change made to the patch file? Try recreating it by manually
  editing the appropriate files and running:
  
    patch-package urbanairship-react-native
  
  If that doesn't work, then it's a bug in patch-package, so please submit a bug
  report. Thanks!

    https://github.com/ds300/patch-package/issues
```

I tried all the suggestions, but got the same error every time. The interesting thing is that the patch is actually applied successfully.

**Comment by ds300** [comment]
> I tried all the suggestions, but got the same error every time. The interesting thing is that the patch is actually applied successfully.

Ooh that is interesting 🤔 

Any chance you could supply your patch file?

**Comment by dccarmo** [comment]
@ds300 Sure thing, there you go:

[urbanairship-react-native+2.2.1.txt](https://github.com/ds300/patch-package/files/3359301/urbanairship-react-native%2B2.2.1.txt)

**Comment by dccarmo** [comment]
After removing `node_modules`, and calling `yarn install`, the error went away and it says the patch was applied successfully. I'm closing this now.

**Comment by faezmurshidi** [comment]
> After removing `node_modules`, and calling `yarn install`, the error went away and it says the patch was applied successfully. I'm closing this now.
> 
> EDIT: The issue was a conflict with another script that also updates the dependencies (`react-native-schemes-manager` in our case).

@dccarmo hi, im also having the same issue. because of react-native-schemes-manager. How did you manage both script?

**Comment by nithin-samudrala** [comment]
same issue how do i solve it
