### ISSUE TITLE
Dependencies dependencies `package.json` patch will fail because of unnecessary noise

### ISSUE THREAD

**Issue by sarpik** [ds300/patch-package#150]
I'm using `npm` and would like to patch `package.json`, but the generated patch cannot be applied after either installing for the first time or re-installing the patched package.

I found a *manual* solution and would like get it automated - it's documented at the bottom.

Everything else is how I got to the solution in the first place.

---

In my project's `package.json`, I have a dependency [`angular2-chartjs`](https://github.com/emn178/angular2-chartjs) - we'll call it `foo`

I need to change `foo`s dependency `bar` into `foo`s peerDependency `bar`

I modify the `node_modules/foo/package.json` and move dependency `bar` to peerDependency.

I patch the `foo` package's `package.json` using
```sh
patch-package foo --exclude 'nothing'
```

(`--exclude nothing` does not mean exclude anything specific - it is there to override the default `--exclude 'package\\.json$', which is annoying and might need another issue)

A patch gets generated. 
I apply it using `patch-package`

Everything works as expected:
Dependency `bar` has been moved to peerDependency `bar`.

Now, if I remove `node_modules/foo` (`npm uninstall foo` / rm by hand) and then install it again - the patch fails.
The same happens if you're installing `foo` for the first time (and this sucks a lot! If someone else clones the patch - they cannot apply it! Same could go with CI/CD (just happened to spot #147 - might be related))

---

Why does this error happen?

Firstly, say I do not change anything in the `foo`s package.json.
If I then run `patch-package foo --exclude 'nothing'`, the patch created has differences! (as you've mentioned @ https://github.com/ds300/patch-package/issues/48#issuecomment-380703140)

this is bad because as I later found out - some fields are different every time, preventing us from applying the patch.
But as I figured - you probably cannot change that.

---

I did this patch-generating procedure twice and kept the previous patch. Using diff, ~~you can clearly see the bug cause~~ I thought this was the bug:

```sh
# generate first patch & move it to foo-old+X.Y.Z.patch
# then generate the second one
# then compare:
$ diff patches/foo+X.Y.Z.patch patches/foo-old+X.Y.Z.patch 
```

```diff
2c2
< index b1c03be..8511b4c 100644
---
> index 34587b5..8511b4c 100644
41c41
< -  "_where": "/tmp/tmp-32231Y7OJUwkOUbcY",
---
> -  "_where": "/tmp/tmp-30754AkVFV65HWUF2",
```

`_where` - it links to a different location everytime you run `npm install` and that's why `patch-package` fails - it cannot apply the `patch` properly.

---

I do not know if this is the only field that's different every time - I just happened to run into it.
If you're going to fix this - consider testing / reading about other fields and could cause the patch applying failure.

---

~~How I fixed it - I deleted the line `"_where": "..."` from the generated patch and everything worked.~~

So I guess you'd need to NOT add any fields, who are different every time, to the generated patch.

---

#### Edit:

I thought I had fixed the issue, but once I tried again, without the `_where` thingy - it still failed!

So what I did now was re-install `foo`, make the change in `foo`s `package.json` and generate the patch once again.

But this time, I used GNUs `patch` instead.

```sh
$ patch node_modules/foo/package.json foo+X.Y.Z.patch

patching file node_modules/foo/package.json
Hunk #1 FAILED at 1.
Hunk #2 succeeded at 32 (offset 2 lines).
Hunk #3 succeeded at 63 (offset 2 lines).
1 out of 3 hunks FAILED -- saving rejects to file node_modules/foo/package.json.rej
```

Huh, interesting, I thought. The `package.json.rej` file looked like this:

```diff
--- package.json
+++ package.json
@@ -1,26 +1,28 @@
 {
-  "_from": "https://registry.npmjs.org/angular2-chartjs/-/angular2-chartjs-0.5.1.tgz",
+  "_from": "angular2-chartjs",
   "_id": "angular2-chartjs@0.5.1",
   "_inBundle": false,
   "_integrity": "sha512-bxEVxVEv7llMcgwuc9jlc5KmuOEngT7ZlUyCddmsXwQQAahrTeNgFJ1Nc1SVQnq2fl2d8efh6m70DqF5beiA+A==",
   "_location": "/angular2-chartjs",
   "_phantomChildren": {},
   "_requested": {
-    "type": "remote",
-    "raw": "angular2-chartjs@https://registry.npmjs.org/angular2-chartjs/-/angular2-chartjs-0.5.1.tgz",
+    "type": "tag",
+    "registry": true,
+    "raw": "angular2-chartjs",
     "name": "angular2-chartjs",
     "escapedName": "angular2-chartjs",
-    "rawSpec": "https://registry.npmjs.org/angular2-chartjs/-/angular2-chartjs-0.5.1.tgz",
-    "saveSpec": "https://registry.npmjs.org/angular2-chartjs/-/angular2-chartjs-0.5.1.tgz",
-    "fetchSpec": "https://registry.npmjs.org/angular2-chartjs/-/angular2-chartjs-0.5.1.tgz"
+    "rawSpec": "",
+    "saveSpec": null,
+    "fetchSpec": "latest"
   },
   "_requiredBy": [
+    "#USER",
     "/"
   ],
   "_resolved": "https://registry.npmjs.org/angular2-chartjs/-/angular2-chartjs-0.5.1.tgz",
   "_shasum": "147204c44bfdfe81f1fab946e1610ee0746b49e6",
-  "_spec": "angular2-chartjs@https://registry.npmjs.org/angular2-chartjs/-/angular2-chartjs-0.5.1.tgz",
-  "_where": "/tmp/tmp-238100spLxZoOc6GL",
+  "_spec": "angular2-chartjs",
+  "_where": "/home/kipras/privateprojects/interactio/panel/node_modules",
   "author": {
     "name": "Chen, Yi-Cyuan",
     "email": "emn178@gmail.com"
```

WOW! Two things:

1. Every single field in this rejected patch hunk starts with an `_`
2. This whole hunk was useless to me (I did NOT introduce any changes that were there - it was just done by `npm` I suppose)

Everything else worked and my other two hunks were applied - the patch worked.

---

What does this mean?

It means that just removing the hunk that failed (which was not even needed for me) from the patch file will make it work:)

So I did - my patch file now looks like this:

```patch
diff --git a/node_modules/angular2-chartjs/package.json b/node_modules/angular2-chartjs/package.json
index 5581221..1b3103d 100644
--- a/node_modules/angular2-chartjs/package.json
+++ b/node_modules/angular2-chartjs/package.json
@@ -30,7 +32,6 @@
   },
   "bundleDependencies": false,
   "dependencies": {
-    "chart.js": "^2.3.0"
   },
   "deprecated": false,
   "description": "Chart.js component for Angular2",
@@ -62,6 +63,7 @@
   "main": "dist/index.js",
   "name": "angular2-chartjs",
   "peerDependencies": {
+    "chart.js": ">= 2 < 3",
     "@angular/common": ">=4.0.0 || ^2.0.0",
     "@angular/compiler": ">=4.0.0 || ^2.0.0",
     "@angular/core": ">=4.0.0 || ^2.0.0"
```

and `patch-package` works now! I re-installed `foo` & can confirm:)

---

I figured out that the `patch-package` succeeded only on the first try, but not the second, was that the changes were already created by me, meaning that no patching was needed!

Obviously, when you rm / re-install the package, the changes that you made to generate the patch are gone, and so now  the real patching needs to be done.

---

### The important bit

Okay, it worked by just manually removing the hunk that failed & wasn't necessary for the patch.
But now I'm asking you - could we automate this?

If this is going to get fixed, I have a couple of issues I'd like to point out:

- [ ] There's no debug mode for the full output, which makes the user use the native `patch` utility if he wants to debug anything - this makes it harder to both report & solve bugs.

- [ ] The way of adding `package.json` into the patch is meh - using `patch-package foo --exclude 'anythingRandom'` to override the default `exclude` is not great, and maybe we could make a better design choice, such as a separate option or something different.

- [ ] Finally, the patch generation for `package.json` itself: do we

1. ignore the properties and their properties (if an object appears), starting with an `_`
    * I don't see myself needing any of them. Mayyyybe someone would want to, I don't know, change the `_shasum` of a package, but I doubt it.
    * Either way - if we make such a change - we need to document it properly to avoid confusion, with a possibility to not use this behavior.

2. or do we delete the hunk that gets generated from those options?

3. or something else entirely, like a `--start-patch` option, which would copy a directory *before* you start patching, so that instead of creating a temporary directory to get a `diff` with side-effects, you'd only compare the before and after of a patched directory.
    * this would probably be tricky, especially if you'd want to modify the patch, which would require the starting directory or otherwise would produce side-effects, just like now.

4. or anything else you can think of?

**Comment by ds300** [comment]
Hi 👋 thanks for the report!! This is very interesting.

I don't think it's worth special-casing the diffing of package.json files for people who use npm. Feels like a lot of mess to deal with for such a niche use case. Would also imply that it's possible to modify transitive dependency trees with patch-package, which it's not. 

Another thing you can do is write a custom postinstall js script to apply the change. Or switch to yarn 🙈

**Comment by sarpik** [comment]
Hey David, thanks for the info! Yes, I've been thinking myself and I realize that special-casing would be a hell lot of a mess.

And true - I could indeed write a custom post-install script, but for now everything's fine as-is. Oh and I've been thinking about `yarn` - would you overall recommend it more than `npm` or nah? Thanks!

**Comment by ds300** [comment]
Yeah yarn is great! You should try it!

**Comment by sarpik** [comment]
Hey thanks for the recommendation David, I've switched to `yarn` and it's awesome! Have a great day :smiley:
