### ISSUE TITLE
playPatch file parse error

### ISSUE THREAD

**Issue by Adam13531** [ds300/patch-package#154]
<Please attach the patch file in question>

**Comment by ds300** [comment]
Hi 👋 This issue needs more detail to be actionable. Can you provide any other information about the problem?

**Comment by ds300** [comment]
gonna close this due to inactivity. Feel free to open another issue if you're still having trouble 🙏

**Comment by Adam13531** [comment]
Whoa, sorry about this! I have no idea how this got filed or what it even refers to any longer. 😢
