### ISSUE TITLE
FileName too long

### ISSUE THREAD

**Issue by chris-topher19** [ds300/patch-package#156]
I am trying to create a patch for some package, But it gives me error

 **unable to stat 'node_modules/react-native-android-location-enabler/android/build/intermediates/javac/debug/compileDebugJavaWithJavac/classes/com/heanoria/library/reactnative/locationenabler/RNAndroidLocationEnablerException.class': _Filename too long._**

**{ status: 128,
  signal: null,
  output:
   [ null,
     <Buffer >,
     <Buffer 66 61 74 61 6c 3a 20 75 6e 61 62 6c 65 20 74 6f 20 73 74 61 74 20 27 6e 6f 64 65 5f 6d 6f 64 75 6c 65 73 2f 72 65 61 63 74
2d 6e 61 74 69 76 65 2d 61 ... > ],
  pid: 5988,
  stdout: <Buffer >,
  stderr:
   <Buffer 66 61 74 61 6c 3a 20 75 6e 61 62 6c 65 20 74 6f 20 73 74 61 74 20 27 6e 6f 64 65 5f 6d 6f 64 75 6c 65 73 2f 72 65 61 63 74 2d 6e 61 74 69 76 65 2d 61 ... >,
  error: null }**.
How to resolve

**Comment by wincjh** [comment]
did you solve it? i wonder how it solve

**Comment by esterkaufman** [comment]
How did you solve this? it happened to me now.

**Comment by Javi** [comment]
For reference, this was a problem with git. You can fix it by running `git config --system core.longpaths true`
