### ISSUE TITLE
Running patch-package after yarn install causes failure

### ISSUE THREAD

**Issue by telmen** [ds300/patch-package#157]
Installed version: `^6.1.2`
React native version: `0.59.10`

After editing react-native code base manually and then run 
```sh 
patch-package react-native 
```
output `patches/react-native+0.59.10.patch` file successfully. But when I try to install deps with `yarn install`, a lib keeps giving me this error.
```sh
**ERROR** Failed to apply patch for package react-native at path
  
    node_modules/react-native

  This error was caused because patch-package cannot apply the following patch file:

    patches/react-native+0.59.10.patch
```

**Comment by NikoFarrelly** [comment]
@telmen did you solve this?

**Comment by telmen** [comment]
Unfortunately, I don't remember. Sorry :(. But I think starting from scratch might have solved it.
