### ISSUE TITLE
Add support for externally hosted patch files

### ISSUE THREAD

**Issue by juho-jaakkola** [ds300/patch-package#158]
As far as I understood from the docs, I always need to commit the patch file into the repository where I want it to be applied.

It would be nice to have support also for external patch files. For example the `composer-patches` module for Composer (PHP package manager) works like this.

See from here, how the location of an externally hosted patch file can be defined in it: https://github.com/cweagans/composer-patches#usage

**Comment by ds300** [comment]
Hello Juho 👋

Thanks for the suggestion. I have to be honest, I'm uncertain this feature
us a good idea, since urls are unreliable as sources of data. Was there a
particular use case you had in mind?

**Comment by juho-jaakkola** [comment]
Example use case could be a pull request made to a public Github repository. If the author of the repo is busy, it may take several weeks or even months to get the fix merged and a new version released.

While waiting for the new fixed release, it would be possible to tell patch-package to use the patch file directly from the open pull request. This is possible in Github by adding `.diff` to the URL of the PR.

Example PR from this repo:
`https://github.com/ds300/patch-package/pull/152`

A patch URL made from that PR:
https://github.com/ds300/patch-package/pull/152.patch

The same `.patch` trick works also with individual commits:
https://github.com/ds300/patch-package/commit/b7633b9b8948baa620650629a6971043101fa19a.patch

**Comment by ds300** [comment]
It's a fun idea but I'm always going to err on the side of reproducible builds, I think. You can always copy the patch into your patches dir yourself :)

Thanks!

**Comment by juho-jaakkola** [comment]
What would be the problem with reproducible builds?

**Comment by ds300** [comment]
Urls are not a stable source of information. If the patch data changes it could prevent your app from building or could even introduce runtime bugs.

**Comment by juho-jaakkola** [comment]
When used with a commit hash URL, the patch content cannot change. Two commits that have different changes cannot have the same commit hash.

As long as a missing URL would be considered a fatal error when applying the patches, the build step of a project couldn't accidentally be completed even if a patch was missing for some reason.

And in the end the project owner could always make the decision separately for each project, whether they want to use external URLs or copy the patches as files into the project repository.
