### ISSUE TITLE
Version range from package.json is not respected

### ISSUE THREAD

**Issue by karol-majewski** [ds300/patch-package#165]
Hello and thank you for your work. 

### Problem

I wanted to patch [`react-universal-component@^3.0.2`](https://github.com/faceyspacey/react-universal-component). I did as instructed:

1. Changed `node_modules/react-universal-component/index.d.ts`
1. Ran `yarn patch-package react-universal-component --include index.d.ts`

### Expected results

- I expected only my change to be included in the patch.
- The patch name should reflect match version of the library I'm using (`^3.0.2`, or a resolved one like `3.0.2` or `3.0.3`).

### Actual results

- Changes I did not make are included in the patch
- The patch is called `react-universal-component+4.0.0.patch`

### Workaround

I order to see the correct patch, I had to:

1. Temporarily lock the version of `react-universal-component` in my `package.json` to `3.0.2`.
1. Run `patch-package`.
1. Revert the changes made to `package.json` and `yarn.lock` in step 1 (because I don't want to have the version locked).

**Comment by OliverJAsh** [comment]
> * Changes I did not make are included in the patch

This happens to be me sometimes and it's because VS Code is running formatters on save. I have to remember to run "save without formatting" instead. 😞 Could that be what's happening to you?

(About that: https://github.com/prettier/prettier-vscode/issues/548 and https://github.com/prettier/prettier-vscode/issues/582.)

As for the weird versioning you're seeing… I have no idea.

**Comment by ds300** [comment]
Yeah not sure what's up with the version issue. patch-package pulls the version string directly out of the package.json for the library.

As for the unintended changes, can you elaborate on what kind of changes they were? Do you happen to still have a patch file that included such changes? I suspect @OliverJAsh is right given that you used `--include`

**Comment by ds300** [comment]
:wave: I'm gonna close this due to inactivity. Feel free to open another issue if you're still having trouble 🙏
