### ISSUE TITLE
Idiot-proof tutorial? "patch-package: command not found"

### ISSUE THREAD

**Issue by Jehoel** [ds300/patch-package#17]
I followed the instructions on the package page, but I can't get it to work:

https://www.npmjs.com/package/patch-package

I did this:

1. `cd ~/git/myproject/src` (directory containing my `package.json` file, my `node_modules` directory is located in the parent `myproject` directory.
2. `npm install patch-package --save` (seems to report `patch-packagr@3.4.0` and its dependencies were installed successfully.
3. I made my tweaks to a package "badpackage" in my `nodue_modules` directory.
4. `patch-package badpackage` gives me this output:
    bash: patch-package: command not found
5. `npm patch-package badpackage` (gives me the `npm` Usage printout)
6. `./patch-package`
    bash: ./patch-package: No such file or directory

Other `npm`-managed commands like `ng` (for `ng serve`, `ng build`, etc) work fine.

I'm using bash 4.4.12 on mingw64.

**Comment by ds300** [comment]
Hey, thanks for the advice. This came up before but I didn't take any action. This time I updated the 'Usage' section: https://github.com/ds300/patch-package/blob/master/README.md#making-patches

Hopefully that makes it easier for people to get started.
