### ISSUE TITLE
Landing Page?

### ISSUE THREAD

**Issue by sw-yx** [ds300/patch-package#171]
Here: https://mobile.twitter.com/djsheldrick/status/1170003961555894273

@fpapado and i would be interested in helping out!

**Comment by ds300** [comment]
Hey @sw-yx 👋 

Big ❤️ for the offer! While I really love elements of that design, the idea of having a landing page in addition to a README seems like more trouble than it's worth to me.

For patch-package I think it makes sense to either have everything in the README as a single source of truth, or to have a tiny readme with the elevator pitch before linking to a full-on docs site (which would no doubt have a landing page). I think the latter might be overkill for such a small tool though, and there's a lot of user benefit to having everything in the readme.

I was really just open-sourcing the design in the hopes that it might be useful for other folks as either inspiration or just to outright use it and change the copy. Also for the internet points, of course 😅

**Comment by sw-yx** [comment]
HAHAHA. ok. i actually share the same feelings, but this came up in drinks with @orta and i figured i'd offer.
