### ISSUE TITLE
can we use patch-package to patch a node_modules/.bin executable?

### ISSUE THREAD

**Issue by sibelius** [ds300/patch-package#173]
can we use patch-package to patch a node_modules/.bin executable?

**Comment by ds300** [comment]
Sure! .bin executables are just symlinks to files inside the package dir :)

**Comment by sibelius** [comment]
should I edit .bin file or another one?

**Comment by ds300** [comment]
It's a symlink so they're the same file! :) Try it out!

**Comment by ds300** [comment]
Gonna close this now, hope you got it figured out :+1:
