### ISSUE TITLE
"No such file or directory" when package install from github tarball

### ISSUE THREAD

**Issue by faragly** [ds300/patch-package#174]
I want to change the sources of this package, but to get access to the [src](https://github.com/Hacker0x01/react-datepicker/blob/master/src/) folder from the repository, I use the installation from the [tar.gz](https://github.com/Hacker0x01/react-datepicker/archive/v2.9.6.tar.gz) archive.
`"react-datepicker": "https://github.com/Hacker0x01/react-datepicker/archive/v2.9.6.tar.gz",`

I create build files for this package in _postinstall_:
`"postinstall": "cd node_modules/react-datepicker && npm i -s && npm run -s build"`

I want to access the non-exportable components in _src_ and the datepicker from _dist_.

But if I start using files from src in my project, then nothing works for me (typescript is used in two files) due to several lines that I would like to patch.

**This is important for understanding why I need such a package installation.**

And now, after I make changes to _src_ (I change a few lines), then the command:

```
npx patch-package react-datepicker
// OR
npx patch-package https://github.com/Hacker0x01/react-datepicker/archive/v2.9.6.tar.gz
```
![image](https://user-images.githubusercontent.com/12684748/65783447-3a73e400-e169-11e9-92ef-e1779ada7f04.png)

Can you help me?

**Comment by faragly** [comment]
I created this patch manually, I hope you make changes to the package to fix this problem.

[react-datepicker+2.9.6.patch.zip](https://github.com/ds300/patch-package/files/3663988/react-datepicker%2B2.9.6.patch.zip)

**Comment by ds300** [comment]
Hi! :wave: 

`patch-package` only works with packages that are not modified by other `postinstall` scripts. I'm sorry if this cost you a lot of time. If I was you I would fork the `react-datepicker` project!

**Comment by faragly** [comment]
react-datepicker are not modified by other postinstall, I just use tarball installation from url

**Comment by ds300** [comment]
Going to close because I couldn't reproduce this issue. Feel free to open a new issue if it's still an issue for you, preferably with a repo which reproduces the issue :pray:
