### ISSUE TITLE
Pre-process patches before applying

### ISSUE THREAD

**Issue by paour** [ds300/patch-package#176]
I would like to create a patch that can change based on some data that is part of the `package.json`, so I can use the same patch for various projects (the need is a bit similar to #167).

Would it be possible to configure `patch-package` so that (without having to change the patches on disk) the patches can be themselves patched (with simple key-value replacement like `%%PORT%%` => `8081` for example) or a filter command, and the result of this processing is used to perform the patch?

**Comment by ds300** [comment]
patch-package can't do this but you could do it yourself easily enough.

e.g.

`myScript.js`
```ts
const replace = require('replace')
const PORT = require('package.json').patchVars.PORT
replace({
  regex: "%%PORT%%",
  replacement: PORT,
  paths: ['patches'],
  recursive: true,
});
```

and then put it before patch-package in your postinstall script

`package.json`
```diff
"scripts": {
-   "postinsall": "patch-package",
+   "postinstall": "node myScript.js && patch-package",
}
```

I haven't tested this exact code, but the general idea should work.

**Comment by paour** [comment]
Thank you very much for taking the time for this in-depth suggestion.
