### ISSUE TITLE
when I run npm install command, I get "undefined postinstall" error

### ISSUE THREAD

**Issue by nekooee** [ds300/patch-package#178]
when I run "npm install" command, I get "undefined postinstall" error
npm v : 6.12.0

```bash
E:\webproject>npm install

> undefined postinstall E:\webproject
> patch-package

patch-package 6.2.0
Applying patches...
element-ui@2.12.0 ✔

audited 27906 packages in 23.751s
found 465 vulnerabilities (2 low, 6 moderate, 457 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by ds300** [comment]
Hi! :wave:

I made a local project called `test` to try out npm (i use yarn for everything) and here's what it logged out

```sh
> test@1.0.0 postinstall /Users/davidsheldrick/code/test
> patch-package

patch-package 6.2.0
Applying patches...
lodash@4.17.15 ✔
npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.

audited 1072 packages in 1.023s
found 0 vulnerabilities
```

So where yours prints `undefined` mine prints `test@1.0.0` so I'm guessing that your package.json file is missing either the `"name"` or `"version"` fields, or both?

**Comment by nekooee** [comment]
Dear ds300,
very thank you. I use "default package.json" of laravel and it doesn't have a name and version!!
I manually added those to my "package.json" and problem resolved.

**Comment by ds300** [comment]
Cool :+1:
