### ISSUE TITLE
How to Patch @jest?

### ISSUE THREAD

**Issue by tihuan** [ds300/patch-package#180]
Hi everyone! Crossposting this question from `jest` here 😁 

source: https://github.com/facebook/jest/issues/7811#issuecomment-540128239

I'm trying to use `patch-package` to patch our project in the meantime and have updated `node_modules/@jest/transform/build/ScriptTransformer.js` with the diff.

However, when I run `yarn patch-package jest`, it says there's no diff (possibly because technically the path is to `node_modules/@jest` instead of `node_modules/jest`. But if I run `yarn patch-package @jest`, then it says `@jest` is not in package.json

Any pointer for this situation? Thanks a lot!

**Comment by ds300** [comment]
the package is called `@jest/transform` so

    yarn patch-package @jest/transform

should do the trick.

**Comment by tihuan** [comment]
Hi @ds300 !! Oh brilliant 👍 ✨ That totally fixed the problem. Thanks so much for your lightning reply. You made my day, sir! 🙏 The patch works perfectly!
