### ISSUE TITLE
Failed to apply patch for package xxx on Windows

### ISSUE THREAD

**Issue by manuhook** [ds300/patch-package#19]
Hello,
Do you have any idean why i have this error on Windows ?

I'm using **yarn install** to try to apply the patch.

![image](https://user-images.githubusercontent.com/531834/30918068-c25bdf6e-a39d-11e7-943f-5ff640f10d94.png)

Thank you :)

**Comment by manuhook** [comment]
PS: Everything is working well on OSX

**Comment by ds300** [comment]
Hi! :)

Windows support is still a little shaky. Do you have the git `core.autocrlf` property set to `true`?

Try running

    git config --global core.autocrlf true

And then check out the repo again, then let me know if it works this time.

**Comment by manuhook** [comment]
Thanks ds300 :)

Unfortunately no luck with `core.autocrlf` set to `true`

**Comment by ds300** [comment]
In that case, can you try running the following in git bash:

    patch -p1 -i patches/react-native-navigation+1.1.213.patch --verbose

and if that doesn't report any errors, then run

    yarn patch-package react-native-navigation

This should create a new version of the patch file. You should test it by removing node modules and running `yarn` again. If the patch is applied successfully, it means it's somehow different to the previous version. Let me know how!

**Comment by manuhook** [comment]
Thanks again,

In git bash :

`patch -p1 -i patches/react-native-navigation+1.1.213.patch --verbose`

![image](https://user-images.githubusercontent.com/531834/30921092-edb51600-a3a5-11e7-8c84-0c3b31e6346e.png)

`yarn patch-package react-native-navigation`

![image](https://user-images.githubusercontent.com/531834/30921600-268480e6-a3a7-11e7-9a97-6d27fb5a026c.png)

I have the same error in the msdos prompt.

Thanks !

**Comment by ds300** [comment]
Hmm 🤔  that seems to be a problem with yarn not invoking commands on windows properly. Looks like you're using an old version of yarn. Maybe you could upgrade yarn and try again?

**Comment by manuhook** [comment]
Better with a yarn update :)

Now the patch created by the last command is identical to the one i was having before ^^;

**Comment by ds300** [comment]
so after creating that new patch, `yarn patch-package` still fails?

**Comment by manuhook** [comment]
yes same error as my first message

**Comment by ds300** [comment]
Any chance you could zip up the patch file and share it with me?

**Comment by manuhook** [comment]
Sure,
I've zip up 3 patches, same problem for each one of them

[patches.zip](https://github.com/ds300/patch-package/files/1340146/patches.zip)

Thanks again,

**Comment by ds300** [comment]
Thanks for the patch files! I've figured out what's causing this issue, and it goes away if I re-write the patch files to get rid of CRLFs before applying them, regardless of whether the source files they're patching have CRLFs or just LFs.

I'll push out a fix tonight. Thanks again for your issue report and the continued collaboration 💯

**Comment by ds300** [comment]
This should be fixed now, in v3.4.1 - Thanks for your patience. Please feel free to reoopen the issue if you find it is still affecting you.
