### ISSUE TITLE
Patch-Package does not work for binary files

### ISSUE THREAD

**Issue by rangav** [ds300/patch-package#193]
Hi Thanks for creating the very useful tool.

I am trying patch `react-native-vector-icons` npm package.

i want to replace the font file `Ionicons.ttf ` with older version file. so created the patch.

But when i run patch-package to apply patch, its not updating the file.

Any help or workaround is appreciated

I am using reach-native v0.61.5

**Comment by rangav** [comment]
I found another library to copy files
https://github.com/webextensions/copy-files-from-to

sharing this incase anyone is having similar issue until its implemented in patch-package

**Comment by ds300** [comment]
Thanks 🙏 

I don't think patch-package will work with binary files any time soon. It's optimised for small source code changes.

Adding a file copy script to your postinstall hook is a good way to go IMO! 👍

**Comment by tmlmt** [comment]
Hey ! Just stumbled upon this issue, as I am in a similar situation where I'd like to patch some font files in a package. 
I was lured by the fact that the patch files included mentions of binaries with some hash index... Do you confirm that binary files are not supported? If that's the case, I think it'd be worth adding a paragraph around that in the README.
