### ISSUE TITLE
support patching side dependency

### ISSUE THREAD

**Issue by lifeart** [ds300/patch-package#194]
for example, I have package `a`, and I want to patch package `b` once `a` installed in `c`.

```
  packageC
  ___________node_modules/
  __________________________/packageA
  __________________________/packageB

```

**Comment by ds300** [comment]
Yeah it can do that! https://github.com/ds300/patch-package#nested-packages

**Comment by ds300** [comment]
Going to close this, let me know if you are still having trouble. 🙏

**Comment by lifeart** [comment]
@ds300 but ti's not about nesting, package with `patch` and package to patch has same level in `node_modules`

**Comment by ds300** [comment]
Ohh I see!! Yeah, this feature has been requested before but I don't want to support it because the potential to cause nightmares for consumers of `patcher` could be quite high. e.g. if another package X depends on the same version of `packageToPatch` you could break package X.

**Comment by lifeart** [comment]
yes, it could break, but you can write this warning into console like `package a has been patched by package b`. 

It's very useful feature if you implementing addon (for ember/angular/webpack) or so, and trying to `hack/extend` original functionality to get extra control on it.

**Comment by Alonski** [comment]
Would love to have this functionality. Maybe ask the user to opt into this after install?
