### ISSUE TITLE
Always attempt all patches, even if one fails

### ISSUE THREAD

**Issue by dobesv** [ds300/patch-package#199]
It would be a convenience if patch-package would attempt to apply all patches, and report errors/success for every patch, rather than exiting immediately on the first failure.

### Use Case 

Sometimes an upstream package is updated to accept my patch, and the patch I have in our project becomes obsolete.  In this case patch-package reports an error that the patch failed, and immediately exits.  I can happily delete the patch file.

However, there is a catch: I have to re-run `patch-package` to ensure that any packages that would have been applied after the one that failed are applied.  I pretty much always forget to do this, resulting in much confusion for me.

**Comment by ds300** [comment]
ah, sorry about the confusion!

Yeah that makes sense, it's a great improvement suggestion, thanks 🙏

**Comment by akwodkiewicz** [comment]
I also needed this behaviour (for me it was CI builds in monorepo project), so I pushed a proposal in PR #217.

**Comment by dobesv** [comment]
Another use case: when building for production, our dev dependencies are not present in node_modules.  patch-package exits as soon as it fails to patch one of those dependencies due it not being there.

**Comment by dobesv** [comment]
@ds300 What do you think about merging the PR or coming up with a different solution?
