### ISSUE TITLE
Should work with npm

### ISSUE THREAD

**Issue by CharlieHess** [ds300/patch-package#2]
Now that we have `npm5`, folks who didn't jump on the `yarn` train are feeling left in the cold when  they try to use this:

```
Error: Command failed: cp '/Users/charlie/slack-desktop/yarn.lock' /var/folders/80/5h887mds2w9_dbcsnt2qh1000000gp/T/tmp-79561F6V6u24aVt5x
cp: /Users/charlie/slack-desktop/yarn.lock: No such file or directory
```

😔😔😔

**Comment by ds300** [comment]
Hi. I'd like to support npm5, and will attempt to do so sometime next week :+1:

**Comment by ds300** [comment]
Forgot to comment to say that `patch-package@3.0.0` supports npm5 🎉
