### ISSUE TITLE
Update documentation for Windows

### ISSUE THREAD

**Issue by alexandrospanagiotidis** [ds300/patch-package#21]
Recently I used patch-package (3.4.0) on macOS (which worked very well) but my colleagues on Windows got an error during `npm install`. I followed the documentation, i.e., I set `autocrlf=true` on Windows but this did not help.

After investigating this issue, I found the following:
- git apply skipped the patches on Windows
- the patches created on macOS could be applied manually on Windows using `patch` (from `git-bash`)
- creating the patches anew on Windows via patch-package worked (i.e., `npm install` did not error out, patches were applied)

I compared the patches created on macOS with those on Windows and found that they were exactly the same, except that the newly created patches on Windows did NOT have CRLF but LF ending.
Then I removed the `autocrlf` setting and forced LF EOL on patch files via `.gitattribute` and then the patches from macOS worked, too.

So, I propose to change the documentation, stating that `autocrlf` is not necessary. Instead, create a `.gitattributes` file in the patches folder containing at least this:
```
*.patch eol=lf
```

**Comment by ds300** [comment]
Thanks, this chimes with what I discovered while debugging #20 last night. I'll try that out and update the README if it goes smoothly.

**Comment by ds300** [comment]
Works like a charm! Would never have realised that you can control EOL characters for particular extensions with `.gitattributes`. Thank you 🙇

**Comment by alexandrospanagiotidis** [comment]
Thank you for patch-package :bow:
Maybe you should note, that the `.gitattributes` work-around only works if people actually use Git and that the files need to be checked out, as the conversion happens during checkout.

**Comment by ds300** [comment]
Good idea, I'm noting that, as well as adding a contextual error message to point people in the right direction when patch application fails for this reason.

**Comment by ds300** [comment]
I've updated the README now to reflect the changes you suggested. Thanks again! Really big improvement!
