### ISSUE TITLE
Support for lerna canary version

### ISSUE THREAD

**Issue by snowystinger** [ds300/patch-package#212]
Lerna canary versions https://github.com/lerna/lerna/tree/master/commands/publish#--canary are suffixed by a sha, this causes patch-package to fail to find a matching installed version to the lockfile version.
https://github.com/ds300/patch-package/blob/master/src/getPackageResolution.ts#L42

**Comment by mikehardy** [comment]
Lerna canary versions are just a specific case of the general semver ability to put build version in: https://semver.org/#spec-item-10

It would be nice for me as well if patch-package handled that aspect of semver as well as https://semver.org/#spec-item-9 (unless it handles pre-release already?)

@snowystinger this seems to be sort of dormant which is a shame, but note that it is possible to actually patch-package patch-package before it does it's postinstall package patching! No joke, you can have a separate directory of patch-package-patches, you can ask patch-package to run with `--patch-dir` to run them, and if those are patch-package patches it will patch itself, then you can run against node_modules.

The whole thing would look like this in package.json:

```json
  "postinstall": "npx patch-package --patch-dir patch-package-patches && npx patch-package",
```
