### ISSUE TITLE
Some patches are corrupt after upgrading

### ISSUE THREAD

**Issue by OliverJAsh** [ds300/patch-package#215]
Hi, I'm in the process of upgrading our version of `patch-package` from 5.1.1 to 6.2.1.

After upgrading, some of my patches failed to apply, or applied but resulted in corrupt files. I checked the release notes and there seems to be no mention of breaking changes, so I decided to file this issue in case other people run into this.

It looks like the format of a patch file has changed slightly?

If you need details of the problematic patches, I can try to share those, but first I wanted to ask is this expected behaviour and whether there is a way to automatically re-generate all patches, so they all use the new format?

**Comment by ds300** [comment]
Oof sorry about this. Yeah the patch format did change in v6, I tried to make it backwards compatible, but should have included a breaking change warning anyway.

You can try reinstalling node_modules without patching, then use the unix `patch` utility to apply the patches before running `patch-package` to regenerate the patch files.

**Comment by OliverJAsh** [comment]
Thanks!
