### ISSUE TITLE
Fails to recognize diffs in package.json

### ISSUE THREAD

**Issue by kumavis** [ds300/patch-package#219]
I was trying to modify a package's `main` field, but `patch-package` reported no changes found

my guess is the `package.json` is intentionally ignored to avoid anomalous diffs made by package managers. but I was also surprised that this didn't work

thanks for patch-package/
its a treasure :trophy:

**Comment by ds300** [comment]
> my guess is the package.json is intentionally ignored to avoid anomalous diffs made by package managers

exactly, yes! the `--exclude` option has a default value of `'/package.json$'`

to work around it you can override the `--exclude` flag to not match package.json, e.g.

    patch-package some-package --exclude '^$'
