### ISSUE TITLE
Allow excluding certain paths from patches

### ISSUE THREAD

**Issue by simdonl** [ds300/patch-package#23]
Every time after I run Yarn the applying Patches gives me the error

    **ERROR** Failed to apply patch for package react-native-audio-toolkit

    This error was caused because Git cannot apply the following patch file:

    patches/react-native-audio-toolkit+1.0.5.patch

    This is usually caused by inconsistent whitespace in the patch file.

When I run ` patch -p1 -i patches/react-native-audio-toolkit+1.0.5.patch`

I got the following for each build file:

    The next patch would create the file node_modules/react-native-audio-toolkit/node_modules/async/applyEachSeries.js,
    which already exists!  Assume -R? [n] 

Is there an option to exclude the build and node_module files from the package from patching?

**Comment by ds300** [comment]
I'm confused, is the issue with react-native-audio-toolkit or react-native-fbsdk? Or both?

Anyway, generally speaking there isn't a way to ignore certain paths with patch-package yet. I thought someone might want this feature at some point. It should be quite straightforward to provide both whitelisting and blacklisting. I'll make that the next feature I work on.

For now you'd have to manually edit the patch file after creating it to remove parts that shouldn't be applied.

**Comment by simdonl** [comment]
Sorry, it's basically for every package with build or node_module folders. In my case It's for both packages. But for now I will edit the packages files, thanks for the workaround!

**Comment by ds300** [comment]
I'm going to change the title of this issue to make it a feature request rather than an error report, hope you don't mind :)

**Comment by ds300** [comment]
This feature is now in patch-package@3.5.0 !
