### ISSUE TITLE
Patch package in root node_modules

### ISSUE THREAD

**Issue by pandaniell** [ds300/patch-package#245]
Not sure if I'm doing something wrong / if this is prevented by design but I have published a plugin which comes with a postinstall script running patch-package and a patch for a 3rd party module in the patches folder, when I install the plugin in a test project with the 3rd party module installed, it errors in the postinstall script `Patch file found for package fastify which is not present at node_modules/fastify`, I feel like it is looking for the node_modules in my plugin but I want it to look at the root node_modules, would this be possible?

**Comment by screetBloom** [comment]
Has this problem been solved?   And I meet the same problem 😭
@daniellwdb

**Comment by kudlav** [comment]
Duplicate of https://github.com/ds300/patch-package/issues/356
