### ISSUE TITLE
prepare doesn't patch when installing npm package indirectly

### ISSUE THREAD

**Issue by midzelis** [ds300/patch-package#26]
Lets say I have a project 'A' with a patch-package and patches to apply to its deps. 
Lets say I have a project 'B' where I want to add 'A' as a dependency. 

When do yarn add 'A' inside of project 'B', the the 'prepare' script isn't run. Meaning, the patches aren't installed properly.

**Comment by ds300** [comment]
Yep this is expected behaviour. patch-package only works for library-consuming projects, and not for libraries themselves. Enabling patching for libraries would be woefully brittle due to version mismatches, conflicts with other libraries, and so forth.
