### ISSUE TITLE
Install package by link/URL to Github PR

### ISSUE THREAD

**Issue by bitttttten** [ds300/patch-package#263]
I had an idea that it would be nice to be able to patch a repo from a github PR:

`npx patch-package https://github.com/software-mansion/react-native-screens/pull/622`

For example. So it would patch the package against this PR. This is nice since perhaps there is a PR that is waiting to be merged or it's blocked for some other reason, but you'd like to introduce the change to your codebase already.

Is this something that you would want to be covered with patch-package? 🤔

**Comment by gomain** [comment]
Pull requests are usually changes to the *source* of a library/framework, not necessarily the *distributed* code that you would normally install via, say, yarn or npm.

If the PR is indeed an installable package, you can install it following this [answer](https://stackoverflow.com/a/18049685/3655260).

**Comment by bitttttten** [comment]
Yeah, that's exactly the problem I am running into at the moment! Installing from a Github comment is probably the best approach unless you want to install more than one PR and the repo is in a consumable state (it's using esmodules, or has a prepare script, etc.).

Another option is creating a Github action that would diff the build again a build on master and the action would then generate a patch file, allowing people to download it. This wouldn't have much adoption since it would need people to install the action and configure it.

I'll close it for now then since perhaps this is out of scope for patch-package and also quite a different problem to solve!
