### ISSUE TITLE
Creating patch file for GitHub dependency fails with ENOENT: no such file or directory

### ISSUE THREAD

**Issue by devattendant** [ds300/patch-package#288]
I was trying to create a patch for a GitHub dependency I added to my projects like this in package.json:
`"react-native-scrollable-tab-view": "git+https://github.com/ptomasroos/react-native-scrollable-tab-view.git"`

And creating the patch fails with:

> • Diffing your files with clean files
> Error: ENOENT: no such file or directory, scandir '/var/folders/bx/qmlnk5tn0lqgn4d_cyplmh5w0000gn/T/tmp-46952lUjIew9dd5Kd/node_modules/react-native-scrollable-tab-view'
>     at Object.readdirSync (node:fs:1067:3)
>     at Object.klawSync [as default] (/.../react-native/node_modules/klaw-sync/klaw-sync.js:13:25)
>     at Object.removeIgnoredFiles (/.../react-native/node_modules/patch-package/dist/filterFiles.js:10:24)
>     at Object.makePatch (/.../react-native/node_modules/patch-package/dist/makePatch.js:123:23)
>     at /.../react-native/node_modules/patch-package/dist/index.js:48:25
>     at Array.forEach (<anonymous>)
>     at Object.<anonymous> (/.../react-native/node_modules/patch-package/dist/index.js:47:22)
>     at Module._compile (node:internal/modules/cjs/loader:1108:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
>     at Module.load (node:internal/modules/cjs/loader:973:32) {
>   errno: -2,
>   syscall: 'scandir',
>   code: 'ENOENT',
>   path: '/var/folders/bx/qmlnk5tn0lqgn4d_cyplmh5w0000gn/T/tmp-46952lUjIew9dd5Kd/node_modules/react-native-scrollable-tab-view'
> }
> /.../react-native/node_modules/patch-package/dist/makePatch.js:184
>         throw e;
>         ^
> 
> Error: ENOENT: no such file or directory, scandir '/var/folders/bx/qmlnk5tn0lqgn4d_cyplmh5w0000gn/T/tmp-46952lUjIew9dd5Kd/node_modules/react-native-scrollable-tab-view'
>     at Object.readdirSync (node:fs:1067:3)
>     at Object.klawSync [as default] (/.../react-native/node_modules/klaw-sync/klaw-sync.js:13:25)
>     at Object.removeIgnoredFiles (/.../react-native/node_modules/patch-package/dist/filterFiles.js:10:24)
>     at Object.makePatch (/.../react-native/node_modules/patch-package/dist/makePatch.js:123:23)
>     at /.../react-native/node_modules/patch-package/dist/index.js:48:25
>     at Array.forEach (<anonymous>)
>     at Object.<anonymous> (/.../react-native/node_modules/patch-package/dist/index.js:47:22)
>     at Module._compile (node:internal/modules/cjs/loader:1108:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
>     at Module.load (node:internal/modules/cjs/loader:973:32) {
>   errno: -2,
>   syscall: 'scandir',
>   code: 'ENOENT',
>   path: '/var/folders/bx/qmlnk5tn0lqgn4d_cyplmh5w0000gn/T/tmp-46952lUjIew9dd5Kd/node_modules/react-native-scrollable-tab-view'
> }

I then looked a bit into makePatch.js and found the automatically created package.json looking like this:
`{"dependencies":{"react-native-scrollable-tab-view":"react-native-scrollable-tab-view@git+https://github.com/ptomasroos/react-native-scrollable-tab-view.git"},"resolutions":{}}`

So just to check if the `react-native-scrollable-tab-view@` is the issue I replaced the `getPackageResolution` call in makePatch.js:49 with the static GitHub URL I used in the package.json above and the patch file was created correctly:
`{"dependencies":{"react-native-scrollable-tab-view":"git+https://github.com/ptomasroos/react-native-scrollable-tab-view.git"},"resolutions":{}}`

I am now wondering if I am linking the GitHub dependency in a wrong way (though I tried various other) or if this is a bug or not expected usage of patch-package at all.

All of this happened on macOS 11.1 with patch-package 6.2.2.

**Comment by devattendant** [comment]
Issue still exists with patch-package 6.4.7 (this time on Windows 10):

> npx patch-package react-native-scrollable-tab-view
> patch-package 6.4.7
> • Creating temporary folder
> • Installing react-native-scrollable-tab-view@1.0.0 with npm
> {
>   status: 1,
>   signal: null,
>   output: [ null, null, null ],
>   pid: 40520,
>   stderr: null,
>   error: null
> }
> 
> ...\react-native\node_modules\patch-package\dist\makePatch.js:218
>         throw e;
>         ^
> {
>   status: 1,
>   signal: null,
>   output: [ null, null, null ],
>   pid: 40520,
>   stdout: null,
>   stderr: null,
>   error: null
> }

And replacing makePatch.js:50 with the following still works:
`fs_extra_1.writeFileSync(tmpRepoPackageJsonPath, JSON.stringify({"dependencies":{"react-native-scrollable-tab-view":"git+https://github.com/ptomasroos/react-native-scrollable-tab-view.git"},"resolutions":{}}));`

**Comment by patrickjm** [comment]
I also get this issue. My repo has this syntax in package.json:

```
"somePackage": "github:someAuthor/somePackage#v0.46.5",
```

**Comment by cstefFlexin** [comment]
replace makePatch:50 with the following: 
`        fs_extra_1.writeFileSync(tmpRepoPackageJsonPath, JSON.stringify({
            dependencies: {
                [packageDetails.name]: getPackageResolution_1.getPackageResolution({
                    packageDetails,
                    packageManager,
                    appPath,
                }).replace(/(.*)@/g, ""),
            },
            resolutions: resolveRelativeFileDependencies_1.resolveRelativeFileDependencies(appPath, appPackageJson.resolutions || {}),
        }));`

**Comment by sebastian-zarzycki-es** [comment]
Same here. A bit annoying.

**Comment by linus-komnick** [comment]
Replacing the fs_extra_1.writeFileSync function starting on line 50 in patch-package/dist/makePatch.js resulted in the same error. Though my error is slightly different than yours:
```
patch-package 6.4.7
• Creating temporary folder
• Installing react-native-pjsip@2.8.0 with npm
• Diffing your files with clean files
Error: ENOENT: no such file or directory, scandir '/var/folders/q1/vl783mk95bs57w4c6_9mpm0c0000gp/T/tmp-22352riq6IRe9r6Pa/node_modules/react-native-pjsip'
    at Object.readdirSync (fs.js:1043:3)
    at Object.klawSync [as default] (/Users/linuskomnick/Noloni/node_modules/klaw-sync/klaw-sync.js:13:25)
    at Object.removeIgnoredFiles (/Users/linuskomnick/Noloni/node_modules/patch-package/dist/filterFiles.js:11:24)
    at Object.makePatch (/Users/linuskomnick/Noloni/node_modules/patch-package/dist/makePatch.js:112:23)
    at /Users/linuskomnick/Noloni/node_modules/patch-package/dist/index.js:52:25
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/linuskomnick/Noloni/node_modules/patch-package/dist/index.js:51:22)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/var/folders/q1/vl783mk95bs57w4c6_9mpm0c0000gp/T/tmp-22352riq6IRe9r6Pa/node_modules/react-native-pjsip'
}
/Users/linuskomnick/Noloni/node_modules/patch-package/dist/makePatch.js:209
        throw e;
        ^

Error: ENOENT: no such file or directory, scandir '/var/folders/q1/vl783mk95bs57w4c6_9mpm0c0000gp/T/tmp-22352riq6IRe9r6Pa/node_modules/react-native-pjsip'
    at Object.readdirSync (fs.js:1043:3)
    at Object.klawSync [as default] (/Users/linuskomnick/Noloni/node_modules/klaw-sync/klaw-sync.js:13:25)
    at Object.removeIgnoredFiles (/Users/linuskomnick/Noloni/node_modules/patch-package/dist/filterFiles.js:11:24)
    at Object.makePatch (/Users/linuskomnick/Noloni/node_modules/patch-package/dist/makePatch.js:112:23)
    at /Users/linuskomnick/Noloni/node_modules/patch-package/dist/index.js:52:25
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/linuskomnick/Noloni/node_modules/patch-package/dist/index.js:51:22)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/var/folders/q1/vl783mk95bs57w4c6_9mpm0c0000gp/T/tmp-22352riq6IRe9r6Pa/node_modules/react-native-pjsip'
}
```
Any ideas how I can solve this?

**Comment by OmgImAlexis** [comment]
@cstefFlexin I'm not really sure what your "fix" is meant todo there as the returned URL is incorrect.

https://github.com/ds300/patch-package/issues/335 fixes the issue.

**Comment by cstefFlexin** [comment]
> @cstefFlexin I'm not really sure what your "fix" is meant todo there as the returned URL is incorrect.
> 
> https://github.com/ds300/patch-package/issues/335 fixes the issue.

I am just replacing the first part of the git url, it seemed to work, but your solutions looks cleaner indeed

**Comment by OmgImAlexis** [comment]
> > @cstefFlexin I'm not really sure what your "fix" is meant todo there as the returned URL is incorrect.
> > #335 fixes the issue.
> 
> I am just replacing the first part of the git url, it seemed to work, but your solution looks cleaner indeed

Oh that makes sense now. I guess with how I was adding the repo your fix wasn't actually doing anything to the returning string.

**Comment by alexthewilde** [comment]
This issue still exists. And @cestef's solution seems to fix it.

**Comment by nkpm** [comment]
> replace makePatch:50 with the following: ` fs_extra_1.writeFileSync(tmpRepoPackageJsonPath, JSON.stringify({ dependencies: { [packageDetails.name]: getPackageResolution_1.getPackageResolution({ packageDetails, packageManager, appPath, }).replace(/(.*)@/g, ""), }, resolutions: resolveRelativeFileDependencies_1.resolveRelativeFileDependencies(appPath, appPackageJson.resolutions || {}), }));`
> 
> it's quite a messy solution, but it still works for me :')

works like a charm. rightaway created a patch for patch-package with patch-package 😵‍💫
