### ISSUE TITLE
Add a way to force error for patch file version mismatch

### ISSUE THREAD

**Issue by jraoult** [ds300/patch-package#314]
While locally the warning for this case is a nice touch, in CI we run an automated dependency management bot. We would love to see `patch-package` blocking the auto-merge to let us intervene and update the patch/check that everything is right in the same PR instead of coming back later to create a new PR just for the patch update.

Following the existing convention, it could be a command-line argument like `--error-on-warning`. I realise this might be a little niche but would you consider this? 

By the way thanks for this amazing tool, this is so helpful and lovely to use 👍

**Comment by alfaproject** [comment]
I don't think this is niche. I just landed on this issue looking for the exact same thing. It's always a waste of CI resources if we want to keep versions matching.

**Comment by charkour** [comment]
This would be a great feature to add!

**Comment by ds300** [comment]
Released in 6.5.0
