### ISSUE TITLE
Create Pull Request from Patch File

### ISSUE THREAD

**Issue by lukebrandonfarrell** [ds300/patch-package#322]
There is currently a `create-issue` command, but I was wondering what are the hurdles to having a `create-pull-request` command? This could significantly enhance the current open source workflow. When I make a patch to a package, I need to to then download the repo, make the changes again and open a PR, which is a huge pain! and I usually just skip doing it.

Have we thought about a `create-pull-request` command? and if so, are there any major blockers to creating it? If not, I'd be happy to contribute :)

**Comment by hipstersmoothie** [comment]
😉 https://www.youtube.com/watch?v=cK5cV4Ejd8o&t=24s

**Comment by lukebrandonfarrell** [comment]
Thanks for the background @hipstersmoothie
