### ISSUE TITLE
Using `--create-issue` result in bad request.

### ISSUE THREAD

**Issue by mthines** [ds300/patch-package#328]
Hey!

When using the `--create-issue`, Github is giving an error saying the `Your request URL is too long.`.

![image](https://user-images.githubusercontent.com/16097850/123537798-9f3ee280-d731-11eb-8e43-1bc131b22f1e.png)

**Comment by bunnybones1** [comment]
Same problem!

**Comment by sergeymild** [comment]
The same problem

**Comment by vladimirevstratov** [comment]
Same problem

**Comment by vladimirevstratov** [comment]
May be use url shortener?

**Comment by nabilfreeman** [comment]
Same

**Comment by orta** [comment]
We should detect if it's too long (~500 chars) and not offer to do the issue

**Comment by bombillazo** [comment]
Cant report a problem via CLI due to this :/

**Comment by ds300** [comment]
Sure!

**Comment by bombillazo** [comment]
Awesome! Here's the PR https://github.com/ds300/patch-package/pull/469

Feedback is welcome

**Comment by bombillazo** [comment]
Hey @ds300 this [pr](https://github.com/ds300/patch-package/issues/328) has been waiting for review for a couple weeks now to fix this, any chance to review it again?
