### ISSUE TITLE
Doesn't handle missing `git`

### ISSUE THREAD

**Issue by firelizzard18** [ds300/patch-package#33]
My CI job was failing at the patch step, with error messages that my patch file couldn't be applied. When I added `apk update && apk add git` (I'm using the apline node docker image), it started working.

patch-package should really say, "Hey, I need git," if that's what it needs to work.

Strange thing is it was working before, when the patch file was simpler...

**Comment by ds300** [comment]
Thanks for the report! I'll add an error message now.

> Strange thing is it was working before, when the patch file was simpler...

patch-package was using the unix `patch`  command for a while to apply patches, but switched to `git` for windows support a couple of months ago. It's possible you were using an old version that used `patch`?

**Comment by ds300** [comment]
Ok done, thanks again for the suggestion! ❤️
