### ISSUE TITLE
Patch a package.json file?

### ISSUE THREAD

**Issue by selfagency** [ds300/patch-package#341]
I'm trying to fix a broken dependency in a node module within my project by altering the dependency version in the module's package.json but the diff doesn't seem to recognize it. Is there a config flag I need or something?

```
📂 code/directlink-portal ⋅  feat/AI-218-Page-scaffolding [$✘!+] via 🐳 default ⋅ 📦 v0.1.23 ⋅  v16.7.0 » 1m5s 
15:11:30 ✖1 ➜ micro node_modules/@storybook/vue/package.json

📂 code/directlink-portal ⋅  feat/AI-218-Page-scaffolding [$✘!+] via 🐳 default ⋅ 📦 v0.1.23 ⋅  v16.7.0 » 12s 
15:12:00 ➜ npx patch-package @storybook/vue              
patch-package 6.4.7
• Creating temporary folder
• Installing @storybook/vue@6.3.7 with npm
• Diffing your files with clean files
⁉️  Not creating patch file for package '@storybook/vue'
⁉️  There don't appear to be any changes.
```

**Comment by luisaverza** [comment]
I think this issue is duplicated.
Maybe this response could help https://github.com/ds300/patch-package/issues/311#issuecomment-835807996

**Comment by zoxon** [comment]
This works for me
```sh
npx patch-package some-package --exclude 'nothing'
```

**Comment by mzvast** [comment]
> ```shell
> --exclude 'nothing'
> ```

It works like charm! Excellent~

**Comment by selfagency** [comment]
Thanks all

**Comment by charlesritchea** [comment]
This might technically "work" but if what youa trying to patch is a dependency that should be a devDependency then it won't have any effect
