### ISSUE TITLE
Patch not installing on production with CI/CD pipe line

### ISSUE THREAD

**Issue by nageshwari17** [ds300/patch-package#344]
Hi Team , 

I am using patch for one of the npm package as required our project. Its working in Local machine in dev mode . But when I build in production its not getting install it .please help me with this

**Comment by esetnik** [comment]
@nageshwari17 how did you solve this?

**Comment by ad9999** [comment]
@nageshwari17 @esetnik were you guys able to solve this ?

**Comment by esetnik** [comment]
I was not. I stopped using patch-package.

**Comment by nmateo** [comment]
Same.. it's a shame it's perfect for our use cases but can't use it in production due to not knowing how to apply it in a react-native build...
