### ISSUE TITLE
[Q] Apply patches for subordinate dependencies after `npm i my_package`

### ISSUE THREAD

**Issue by Harasz** [ds300/patch-package#379]
Hi!

My team is developing an open source npm package, we are using your library to patch our broken dependencies. We are not bundling our dependencies, so if someone is trying to install our package all of our dependencies are installed from npm registry, so they are not patched. Currently, users of our package have to apply patches themselves. We want to make it more automated. So after our package is installed, we want `patch-pacakge` to automatically apply patches. Probably the reason for failing this for us is that our package is under directory `node_modules/package` and our broken dependencies are under  `node_modules/dependency` and not under `node_modules/package/node_modules/dependency`.

Can anyone tell us what we can do in this situation to make it work?

**Comment by david-mohr** [comment]
This doesn't appear to be a supported use case: https://github.com/ds300/patch-package/issues/198.

But there is a suggested workaround: https://github.com/ds300/patch-package/issues/198#issuecomment-873975267 which may or may not suffice depending on your use case
