### ISSUE TITLE
patch react-native android

### ISSUE THREAD

**Issue by danilobuerger** [ds300/patch-package#38]
From the README.md:
> Sometimes forks need extra build steps, e.g. with react-native for Android. Forget that noise.

Is it actually possible to patch a java file from react-native? As far as I know, react-native includes an aar and thus changes on the source files will not have any effect.

**Comment by ds300** [comment]
Hi Danilo,

You are correct. Sorry if the README caused some confusion. The line you
quoted is not supposed to imply that patching java source files will work
for react native. It should only mean that if you fork react-native then
you also need to figure out how to build the android distribution before
you can use your forked version of react-native for building android apps.

Cheers,

David

**Comment by danilobuerger** [comment]
Hi David, thanks for clearing that up!
Danilo
