### ISSUE TITLE
Each second patch-package run reverses patches

### ISSUE THREAD

**Issue by sherlock1982** [ds300/patch-package#39]
Version: 5.1.0
NPM: 5.6.0
NodeJS: 8.9.1

I created a patch for a package.
Every first time I do "npm run prepare" patch is applied and every second time patch is reversed.

UPDATE: 5.0.0 works perfectly

**Comment by ds300** [comment]
Thanks for the report! This is an extremely intriguing issue. I'll look in to it tomorrow.

**Comment by ds300** [comment]
A fix for this was published in 5.1.1. Thanks again for submitting the issue ❤️
