### ISSUE TITLE
**ERROR** Failed to apply patch for package react-native-maps at path   

### ISSUE THREAD

**Issue by harish-narra** [ds300/patch-package#405]
node_modules/react-native-maps

  This error was caused because patch-package cannot apply the following patch file:

    patches/react-native-maps+0.26.1.patch

  Try removing node_modules and trying again. If that doesn't work, maybe there was
  an accidental change made to the patch file? Try recreating it by manually
  editing the appropriate files and running:
  
    patch-package react-native-maps
  
  If that doesn't work, then it's a bug in patch-package, so please submit a bug
  report. Thanks!

    https://github.com/ds300/patch-package/issues

Tried to removed node modules many times, still getting same

**Comment by SkipCat** [comment]
I have the same issue with react-native-document-picker but only in CircleCI

Full comment here https://github.com/ds300/patch-package/issues/419#issuecomment-1263328660
