### ISSUE TITLE
Does not support pnpm

### ISSUE THREAD

**Issue by arobinson** [ds300/patch-package#413]
```
patch-package 6.4.7

**ERROR** No package-lock.json, npm-shrinkwrap.json, or yarn.lock file.

You must use either npm@>=5, yarn, or npm-shrinkwrap to manage this project's
dependencies.
```

pnpm does not use any of these files. It uses `pnpm-lock.yaml`

**Comment by arobinson** [comment]
I'm not sure it really should support it well. pnpm will hard-link these files, so if the package is patched, it is patched for the entire computer, not just the working copy. As a result the patch will affect the entire computer.

**Comment by orta** [comment]
Closing as this works well in pnpm natively 👍🏻 and we document this in the README

**Comment by karlhorky** [comment]
## Converter script: `patch-package` patches to pnpm patches

If you're looking to move from `patch-package` to pnpm for patches, here's my quick version of a script to convert from `patch-package` patches to pnpm patches:

- https://github.com/karlhorky/pnpm-tricks#convert-patch-package-patches-to-pnpm-patches

<img width="1437" height="817" alt="Image" src="https://github.com/user-attachments/assets/6daaaf33-c0a9-457d-88b4-afc92b274b62" />

I also asked whether such a converter would be considered to be a part of pnpm in future, as an easier, built-in way to migrate from `patch-package` to pnpm:

- https://github.com/pnpm/pnpm/issues/10087
