### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by keeganstreet** [ds300/patch-package#44]
The tests are currently failing. I thought it might be my local environment, but it looks like they are failing on TravisCI as well: https://travis-ci.org/ds300/patch-package/

**Comment by ds300** [comment]
Works on my machine! Closing this issue 🚫 

... just kidding :)

I've been meaning to take a look at making the tests work on linux and windows for a long time now. Going to have a crack at it tonight. Hopefully if things are in better shape people will be more open to contributing.

Thanks for raising this issue and giving me a kick in the butt! :+1:

**Comment by keeganstreet** [comment]
Haha thanks mate :) I might be able to contribute some tests once the current tests are passing.

**Comment by ds300** [comment]
Just merged #45 and now tests are passing 🎉 So I'm going to close this. Thanks again!
