### ISSUE TITLE
Patch-package in react-native release (gradlew assembleRelease)

### ISSUE THREAD

**Issue by nmateo** [ds300/patch-package#451]
Hey i use patch package to patch some react-native package but can't seem to find how to apply them in release build

>  (./android/gradlew assembleRelease)

However my patch works perfectly in dev with expo go or npx react-native run-android,
Thanks in advance

**Comment by hatem-72** [comment]
What kind of file are you trying to patch ?
I use patch-package extensively in my react-native apps and it is working great.

I don't use expo though.
