### ISSUE TITLE
Security issue - patch-package@6.5.1 requires yaml@^1.10.2

### ISSUE THREAD

**Issue by idrissakhi** [ds300/patch-package#464]
Uncaught Exception in GitHub repository eemeli/yaml prior to 2.2.2.

resolve, bump yaml to at least 2.2.2

**Comment by rsanchez** [comment]
Looks like this was addressed by #465, but it's only on the master branch so far. There's no tagged release yet.

**Comment by ds300** [comment]
Yep just published v7.0.0 with this fix in
