### ISSUE TITLE
Warn when patch exists for old version of package

### ISSUE THREAD

**Issue by Daniel15** [ds300/patch-package#498]
At Meta, I've seen a few cases where a package was updated but the patch wasn't redone for the new version. It would be nice for patch-package to warn on install/upgrade if a patch exists for an older version of an installed package. Something like this maybe:

> Package `foo` has a patch for version 1.0, but version 2.1 is currently installed. Do you need to create a patch for the new version?

**Comment by karlhorky** [comment]
@Daniel15 not sure if I'm understanding your description above, but as far as I understand I've never had this problem, and use `patch-package` actively, with many package upgrades per week.

Do you think it could have anything to do with the current bug of outdated patches not being removed?

- #480

**Comment by Daniel15** [comment]
@karlhorky  The problem is that people don't even know the patch exists, and when they update a package, they don't know that they have to re-do the patch. A big warning at some point (like when doing an upgrade or when it deletes the old patch) would help.

**Comment by karlhorky** [comment]
> they have to re-do the patch

Hm yeah here's the divergence - this does not happen for us.

What has happened in our projects (since years) is that the old patch is still applied to the new version - unless the patch doesn't apply, in which case `patch-package` does fail with a big red error.

**Comment by karlhorky** [comment]
There is also a flag to turn the warning mentioned in my previous comment into an error.

**Comment by Daniel15** [comment]
I figured this out - We have postinstall scripts disabled for security reasons
![image](https://github.com/ds300/patch-package/assets/91933/58b9eb59-f468-4871-89ef-8dc7ad6bb767)

So the only time `patch-package` was running was during the initial patching, **not** on package upgrades. doh. I'll see if we can fix this somehow.
