### ISSUE TITLE
Remove colon character from patch filenames

### ISSUE THREAD

**Issue by keeganstreet** [ds300/patch-package#5]
Hi @ds300,

Great work on this!

Can I suggest that patches are named as `some-package 3.14.15.patch` instead of `some-package:3.14.15.patch`?

The colon character is invalid for filenames on Windows. If you clone a repo with colons in the filenames onto a Windows machine, the files will be renamed. Apart from this issue, `patch-package` appears to work on Windows (when used via Git Bash which includes GNU patch).

Spaces are not valid npm package names, so I think the space will serve just as well as the colon as a separator.

Cheers,
Keegan

**Comment by ds300** [comment]
Thanks for the suggestion. I had no idea windows support would be so easy to provide!

How about `+` instead of space? Or could you provide some other alternative characters? Something about the idea of putting spaces in filenames scares me at a deep instinctual level, although I couldn't say why so maybe it's an irrational fear :-)

**Comment by keeganstreet** [comment]
`+` would work just as well. It is not valid for npm package names, but it is valid in filenames.

Would you like me to make a PR for this? I would suggest that new patches are named with a plus instead of a colon, but `findPatchFiles` looks for patches with both the current and new naming conventions so the change is backwards compatible.

**Comment by ds300** [comment]
Yeah backwards compatibility is a must. I'll do this later tonight unless you submit a PR first. Should be a tiny change.

**Comment by ds300** [comment]
![image](https://user-images.githubusercontent.com/1242537/28634120-1b3f1c82-722e-11e7-8c76-c6a4b25880ef.png)

**Comment by keeganstreet** [comment]
Thanks @ds300 !
