### ISSUE TITLE
Script doesn't run if you use yarn's upgrade-interactive

### ISSUE THREAD

**Issue by Slessi** [ds300/patch-package#50]
As in title, if you use `yarn upgrade-interactive` then `patch-package` is not run

**Comment by ds300** [comment]
Hi! :wave: Thanks for the report.

It seems yarn doesn't run lifecycle hooks at all after upgrade-interactive. Weird. Not even with postinstall-postinstall installed. Found some discussion over here https://github.com/yarnpkg/yarn/issues/2878

**Comment by ds300** [comment]
I'm going to close this due to inactivity. Hopefully yarn v2 will let us fix this 🤞
