### ISSUE TITLE
Support for yarn berry

### ISSUE THREAD

**Issue by KrzysztofZawisla** [ds300/patch-package#528]
Would be awesome to have a support for yarn at berry version. Right now, I'm unable to use patch-package with this specific version of yarn.

**Comment by thegdznet** [comment]
Hello.

You can try "yarn patch [package]" directly with yarn Berry.  Don't forget to follow instructions displayed by yarn (i.e. "Once you are done run yarn patch-commit -s...").

Yarn will create a patch file in ".yarn/patches" and modify package.json for You.

Hoping it will help,
