### ISSUE TITLE
"Include" and "exclude" path documentation is incorrect

### ISSUE THREAD

**Issue by kmjennison** [ds300/patch-package#54]
The documentation for `--include` and `--exclude` says "Paths are relative to the root dir of the package to be patched." However, the [`fileName` here](https://github.com/ds300/patch-package/blob/master/src/makePatch.ts#L140) appears to be relative to the parent repository. I see a prefix of `node_modules/the-package-being-patched/` for every file.

Documentation should read: "Paths are relative to your project's root directory."

**Comment by ds300** [comment]
Hi! :wave: You're completely right. Thanks for raising the issue :bow: I'll fix this asap.

**Comment by ds300** [comment]
I decided to fix the implementation to be scoped properly, rather than change the docs. Thanks again! 👍
