### ISSUE TITLE
Specify directory for patches

### ISSUE THREAD

**Issue by andreyantipov** [ds300/patch-package#57]
Hello @ds300 David, i'd like to propose feature:

Specify  directory where to store all patches - for example /.patches

**Comment by lots0logs** [comment]
@ds300 Is this something you would consider?

**Comment by ds300** [comment]
Hi! 👋 Thanks for the suggestion and sorry it's taken me so long to get around to replying. Someone implemented this feature a while back. It's --patch-dir at the cli, and it's available in the latest beta release. I haven't documented it in the readme yet though. Will do that soon.

**Comment by ds300** [comment]
I just released 6.0.0 which has this feature :tada:
