### ISSUE TITLE
Should we switch from postinstall-prepare to postinstall-postinstall?

### ISSUE THREAD

**Issue by OliverJAsh** [ds300/patch-package#58]
I noticed this was updated in https://github.com/ds300/patch-package/commit/f9fb13b2a25c60991ff88f0efe0399f6f5f6f623 but there's no sign of why. Do we need to switch, or is it safe to continue using `postinstall-prepare`?

**Comment by ds300** [comment]
You don't need to switch unless you use, or might one day use, [the `npm ci` command](https://docs.npmjs.com/cli/ci) to install your dependencies. `npm ci` does not trigger the `prepare` lifecycle hook, but does trigger the `postinstall` hook. I changed the docs in that commit for maximum compatibility. See #46

**Comment by OliverJAsh** [comment]
Perfect, thanks!
