### ISSUE TITLE
Temporary files (e.g. build products) lead to large diff

### ISSUE THREAD

**Issue by KevinVlaanderen** [ds300/patch-package#60]
We are using patch-package to patch react-native. Unfortunately, compiling react-native results in Android/iOS build files within the node_modules folder. This leads to two problems:

- If no exclude option is provided, `npx patch-package react-native` results in a huge diff file, because all build files are seen as new and therefore added to the diff.
- When adding the exclude option to ignore all build files, a new process is spawned to git reset each of them. This takes longer than we were willing to wait.

When debugging this, we noticed that the approach to creating a diff contains some inefficiencies:

- The diff command is ran twice; once to determine files to exclude, and once to obtain the final diff.
- Excluded files are only removed from the set very late (prior to creating the final diff. This means unnecessary copying of files.
- Excluded files are reset one per one. For every excluded file, a new 'git reset' process is spawned. This is very expensive. (see below)

I am working on a MR.

**Comment by ds300** [comment]
Awesome! Can't wait to see it! :-)

**Comment by pke** [comment]
This seems to be still a problem. The diff seems to be run against the files in the node_modules folder of that package (incl build artifacts).
For the diff algo it looks like the build artifacts are new files and adds them all to the patch.
But I guess there is no real solution other than manually delete the build artifacts and then create the patch.

**Comment by ds300** [comment]
@pke you can also use the --exclude option
