### ISSUE TITLE
Tests do not run on Mac

### ISSUE THREAD

**Issue by KevinVlaanderen** [ds300/patch-package#66]
There seem to be multiple issues, but a recurring theme is the 'replace' command. I am not familiar with it. Do you think we can replace (no pun intended) with something more cross-platform?

 ✘  ~/Workspace/patch-package   portable-tests  yarn test integration-tests
yarn run v1.7.0
$ ./run-tests.sh integration-tests
$ rimraf dist patch-package.test*.tgz
$ tsc
success Wrote tarball to "patch-package.test.1529268562.tgz".
 FAIL  integration-tests/resolve-relative-paths/resolve-relative-paths.test.ts
  ● Console

    console.error src/spawnSafe.ts:14
      error An unexpected error occurred: "ENOENT: no such file or directory, open '/Users/Kevin/Library/Caches/Yarn/v1/.tmp/015be32444d511aa07db3fc7c800959e/integration-tests/include-exclude-paths/package.json'".

    console.error integration-tests/runIntegrationTest.ts:26
      Add patch-package
      [1/4] Resolving packages...
      info If you think this is a bug, please open a bug report with the information provided in "/private/var/folders/vx/mfw86xgx2tsgxqyxtk1gmg840000gp/T/tmp-316857KNKfsuOvuCR/yarn-error.log".
      info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

      error An unexpected error occurred: "ENOENT: no such file or directory, open '/Users/Kevin/Library/Caches/Yarn/v1/.tmp/015be32444d511aa07db3fc7c800959e/integration-tests/include-exclude-paths/package.json'".

  ● Test resolve-relative-paths: › should exit with 0 status

    expect(received).toBe(expected)

    Expected value to be (using ===):
      0
    Received:
      1

      at Object.<anonymous> (integration-tests/runIntegrationTest.ts:28:29)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:118:7)

  ● Test resolve-relative-paths: › should produce some snapshots

    expect(received).toBeTruthy()

    Expected value to be truthy, instead received
      null

      at Object.<anonymous> (integration-tests/runIntegrationTest.ts:45:47)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:118:7)

 FAIL  integration-tests/include-exclude-paths/include-exclude-paths.test.ts
  ● Console

    console.error src/spawnSafe.ts:14
      error An unexpected error occurred: "ENOENT: no such file or directory, chmod '/Users/Kevin/Library/Caches/Yarn/v1/.tmp/015be32444d511aa07db3fc7c800959e/integration-tests/scoped-package/patches/@types/left-pad+1.1.1.patch'".

    console.error integration-tests/runIntegrationTest.ts:26
      add patch-package
      [1/4] Resolving packages...
      info If you think this is a bug, please open a bug report with the information provided in "/private/var/folders/vx/mfw86xgx2tsgxqyxtk1gmg840000gp/T/tmp-31682lQzTJSGLu3gv/yarn-error.log".
      info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

      error An unexpected error occurred: "ENOENT: no such file or directory, chmod '/Users/Kevin/Library/Caches/Yarn/v1/.tmp/015be32444d511aa07db3fc7c800959e/integration-tests/scoped-package/patches/@types/left-pad+1.1.1.patch'".

  ● Test include-exclude-paths: › should exit with 0 status

    expect(received).toBe(expected)

    Expected value to be (using ===):
      0
    Received:
      1

      at Object.<anonymous> (integration-tests/runIntegrationTest.ts:28:29)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:118:7)

  ● Test include-exclude-paths: › should produce some snapshots

    expect(received).toBeTruthy()

    Expected value to be truthy, instead received
      null

      at Object.<anonymous> (integration-tests/runIntegrationTest.ts:45:47)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:118:7)

 FAIL  integration-tests/include-exclude-regex-relativity/include-exclude-regex-relativity.test.ts
  ● Console

    console.error src/spawnSafe.ts:14
      error An unexpected error occurred: "ENOENT: no such file or directory, utime '/Users/Kevin/Library/Caches/Yarn/v1/.tmp/015be32444d511aa07db3fc7c800959e/integration-tests/broken-patch-file/patches/left-pad+1.1.3.patch'".

    console.error integration-tests/runIntegrationTest.ts:26
      add patch-package
      [1/4] Resolving packages...
      info If you think this is a bug, please open a bug report with the information provided in "/private/var/folders/vx/mfw86xgx2tsgxqyxtk1gmg840000gp/T/tmp-31684qFmBKNPb01Pk/yarn-error.log".
      info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

      error An unexpected error occurred: "ENOENT: no such file or directory, utime '/Users/Kevin/Library/Caches/Yarn/v1/.tmp/015be32444d511aa07db3fc7c800959e/integration-tests/broken-patch-file/patches/left-pad+1.1.3.patch'".

  ● Test include-exclude-regex-relativity: › should exit with 0 status

    expect(received).toBe(expected)

    Expected value to be (using ===):
      0
    Received:
      1

      at Object.<anonymous> (integration-tests/runIntegrationTest.ts:28:29)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:118:7)

 FAIL  integration-tests/scoped-package/scoped-package.test.ts (7.041s)
  ● Console

    console.error src/spawnSafe.ts:14
      ./scoped-package.sh: line 12: replace: command not found

    console.error integration-tests/runIntegrationTest.ts:26
      add patch-package
      [1/4] Resolving packages...
      [2/4] Fetching packages...
      [3/4] Linking dependencies...
      [4/4] Building fresh packages...
      success Saved lockfile.
      success Saved 83 new dependencies.
      info Direct dependencies
      └─ patch-package@6.0.0-7
      info All dependencies
      ├─ ansi-align@2.0.0
      ├─ ansi-styles@3.2.1
      ├─ boxen@1.3.0
      ├─ camelcase@4.1.0
      ├─ capture-stack-trace@1.0.0
      ├─ ci-info@1.1.3
      ├─ cli-boxes@1.0.0
      ├─ color-convert@1.9.2
      ├─ color-name@1.1.1
      ├─ configstore@3.1.2
      ├─ create-error-class@3.0.2
      ├─ cross-spawn@5.1.0
      ├─ crypto-random-string@1.0.0
      ├─ deep-extend@0.6.0
      ├─ dot-prop@4.2.0
      ├─ duplexer3@0.1.4
      ├─ escape-string-regexp@1.0.5
      ├─ execa@0.7.0
      ├─ fs-extra@4.0.3
      ├─ fs.realpath@1.0.0
      ├─ glob@7.1.2
      ├─ global-dirs@0.1.1
      ├─ got@6.7.1
      ├─ graceful-fs@4.1.11
      ├─ has-ansi@2.0.0
      ├─ has-flag@3.0.0
      ├─ import-lazy@2.1.0
      ├─ imurmurhash@0.1.4
      ├─ inflight@1.0.6
      ├─ inherits@2.0.3
      ├─ ini@1.3.5
      ├─ is-ci@1.1.0
      ├─ is-fullwidth-code-point@2.0.0
      ├─ is-installed-globally@0.1.0
      ├─ is-npm@1.0.0
      ├─ is-obj@1.0.1
      ├─ is-path-inside@1.0.1
      ├─ is-redirect@1.0.0
      ├─ is-retry-allowed@1.1.0
      ├─ is-stream@1.1.0
      ├─ isexe@2.0.0
      ├─ jsonfile@4.0.0
      ├─ latest-version@3.1.0
      ├─ lowercase-keys@1.0.1
      ├─ lru-cache@4.1.3
      ├─ make-dir@1.3.0
      ├─ npm-run-path@2.0.2
      ├─ os-tmpdir@1.0.2
      ├─ p-finally@1.0.0
      ├─ package-json@4.0.1
      ├─ patch-package@6.0.0-7
      ├─ path-is-absolute@1.0.1
      ├─ path-is-inside@1.0.2
      ├─ path-key@2.0.1
      ├─ pify@3.0.0
      ├─ prepend-http@1.0.4
      ├─ pseudomap@1.0.2
      ├─ rc@1.2.8
      ├─ registry-auth-token@3.3.2
      ├─ registry-url@3.1.0
      ├─ rimraf@2.6.2
      ├─ semver-diff@2.1.0
      ├─ semver@5.5.0
      ├─ shebang-command@1.2.0
      ├─ shebang-regex@1.0.0
      ├─ signal-exit@3.0.2
      ├─ slash@1.0.0
      ├─ strip-ansi@3.0.1
      ├─ strip-eof@1.0.0
      ├─ strip-json-comments@2.0.1
      ├─ supports-color@5.4.0
      ├─ term-size@1.2.0
      ├─ timed-out@4.0.1
      ├─ tmp@0.0.31
      ├─ unique-string@1.0.0
      ├─ universalify@0.1.1
      ├─ unzip-response@2.0.1
      ├─ update-notifier@2.5.0
      ├─ url-parse-lax@1.0.0
      ├─ which@1.3.1
      ├─ widest-line@2.0.0
      ├─ write-file-atomic@2.3.0
      └─ yallist@2.1.2
      $ patch-package
      patch-package: Applying patches...
      @types/left-pad@1.1.1 ✔
      SNAPSHOT: left-pad typings should contain patch-package
      // Definitions by: Zlatko patch-package <https://github.com/Goldsmith42/>
      END SNAPSHOT
      modify add.d.t.s

      ./scoped-package.sh: line 12: replace: command not found

  ● Test scoped-package: › should exit with 0 status

    expect(received).toBe(expected)

    Expected value to be (using ===):
      0
    Received:
      127

      at Object.<anonymous> (integration-tests/runIntegrationTest.ts:28:29)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:118:7)

 FAIL  integration-tests/delete-scripts/delete-scripts.test.ts
  ● Console

    console.error src/spawnSafe.ts:14
      ./delete-scripts.sh: line 7: replace: command not found

    console.error integration-tests/runIntegrationTest.ts:26
      install without error because package.json is sanitized
      [1/4] Resolving packages...
      [2/4] Fetching packages...
      [3/4] Linking dependencies...
      [4/4] Building fresh packages...
      success Saved lockfile.
      success Saved 83 new dependencies.
      info Direct dependencies
      └─ patch-package@6.0.0-7
      info All dependencies
      ├─ ansi-align@2.0.0
      ├─ ansi-styles@3.2.1
      ├─ boxen@1.3.0
      ├─ camelcase@4.1.0
      ├─ capture-stack-trace@1.0.0
      ├─ ci-info@1.1.3
      ├─ cli-boxes@1.0.0
      ├─ color-convert@1.9.2
      ├─ color-name@1.1.1
      ├─ configstore@3.1.2
      ├─ create-error-class@3.0.2
      ├─ cross-spawn@5.1.0
      ├─ crypto-random-string@1.0.0
      ├─ deep-extend@0.6.0
      ├─ dot-prop@4.2.0
      ├─ duplexer3@0.1.4
      ├─ escape-string-regexp@1.0.5
      ├─ execa@0.7.0
      ├─ fs-extra@4.0.3
      ├─ fs.realpath@1.0.0
      ├─ glob@7.1.2
      ├─ global-dirs@0.1.1
      ├─ got@6.7.1
      ├─ graceful-fs@4.1.11
      ├─ has-ansi@2.0.0
      ├─ has-flag@3.0.0
      ├─ import-lazy@2.1.0
      ├─ imurmurhash@0.1.4
      ├─ inflight@1.0.6
      ├─ inherits@2.0.3
      ├─ ini@1.3.5
      ├─ is-ci@1.1.0
      ├─ is-fullwidth-code-point@2.0.0
      ├─ is-installed-globally@0.1.0
      ├─ is-npm@1.0.0
      ├─ is-obj@1.0.1
      ├─ is-path-inside@1.0.1
      ├─ is-redirect@1.0.0
      ├─ is-retry-allowed@1.1.0
      ├─ is-stream@1.1.0
      ├─ isexe@2.0.0
      ├─ jsonfile@4.0.0
      ├─ latest-version@3.1.0
      ├─ lowercase-keys@1.0.1
      ├─ lru-cache@4.1.3
      ├─ make-dir@1.3.0
      ├─ npm-run-path@2.0.2
      ├─ os-tmpdir@1.0.2
      ├─ p-finally@1.0.0
      ├─ package-json@4.0.1
      ├─ patch-package@6.0.0-7
      ├─ path-is-absolute@1.0.1
      ├─ path-is-inside@1.0.2
      ├─ path-key@2.0.1
      ├─ pify@3.0.0
      ├─ prepend-http@1.0.4
      ├─ pseudomap@1.0.2
      ├─ rc@1.2.8
      ├─ registry-auth-token@3.3.2
      ├─ registry-url@3.1.0
      ├─ rimraf@2.6.2
      ├─ semver-diff@2.1.0
      ├─ semver@5.5.0
      ├─ shebang-command@1.2.0
      ├─ shebang-regex@1.0.0
      ├─ signal-exit@3.0.2
      ├─ slash@1.0.0
      ├─ strip-ansi@3.0.1
      ├─ strip-eof@1.0.0
      ├─ strip-json-comments@2.0.1
      ├─ supports-color@5.4.0
      ├─ term-size@1.2.0
      ├─ timed-out@4.0.1
      ├─ tmp@0.0.31
      ├─ unique-string@1.0.0
      ├─ universalify@0.1.1
      ├─ unzip-response@2.0.1
      ├─ update-notifier@2.5.0
      ├─ url-parse-lax@1.0.0
      ├─ which@1.3.1
      ├─ widest-line@2.0.0
      ├─ write-file-atomic@2.3.0
      └─ yallist@2.1.2
      unsnitize package.json

      ./delete-scripts.sh: line 7: replace: command not found

  ● Test delete-scripts: › should exit with 0 status

    expect(received).toBe(expected)

    Expected value to be (using ===):
      0
    Received:
      127

      at Object.<anonymous> (integration-tests/runIntegrationTest.ts:28:29)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:118:7)

  ● Test delete-scripts: › should produce some snapshots

    expect(received).toBeTruthy()

    Expected value to be truthy, instead received
      null

      at Object.<anonymous> (integration-tests/runIntegrationTest.ts:45:47)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:118:7)

 FAIL  integration-tests/ignore-whitespace/ignore-whitespace.test.ts (8.274s)
  ● Console

    console.error src/spawnSafe.ts:14
      SNAPSHOT: empty changeset when adding whitespace
      ⁉️  Not creating patch file for package 'alphabet'
      ⁉️  There don't appear to be any changes.
      END SNAPSHOT
      ./ignore-whitespace.sh: line 20: replace: command not found

    console.error integration-tests/runIntegrationTest.ts:26
      add patch-package
      [1/4] Resolving packages...
      [2/4] Fetching packages...
      [3/4] Linking dependencies...
      [4/4] Building fresh packages...
      success Saved lockfile.
      success Saved 1 new dependency.
      info Direct dependencies
      └─ patch-package.test.1529268562.tgz@0.0.0
      info All dependencies
      └─ patch-package.test.1529268562.tgz@0.0.0
      add random bits of whitespace
      try to make patch file (should be empty)
      ☑ Creating temporary folder
      ☑ Building clean node_modules with yarn
      ☑ Diffing your files with clean files
      make a change to line a

      SNAPSHOT: empty changeset when adding whitespace
      ⁉️  Not creating patch file for package 'alphabet'
      ⁉️  There don't appear to be any changes.
      END SNAPSHOT
      ./ignore-whitespace.sh: line 20: replace: command not found

  ● Test ignore-whitespace: › should exit with 0 status

    expect(received).toBe(expected)

    Expected value to be (using ===):
      0
    Received:
      127

      at Object.<anonymous> (integration-tests/runIntegrationTest.ts:28:29)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:118:7)

 FAIL  integration-tests/reverse-option/reverse-option.test.ts (5.697s)
  ● Console

    console.error src/spawnSafe.ts:14
      ./reverse-option.sh: line 8: replace: command not found

    console.error integration-tests/runIntegrationTest.ts:26
      add patch-package
      [1/4] Resolving packages...
      [2/4] Fetching packages...
      [3/4] Linking dependencies...
      [4/4] Building fresh packages...
      success Saved lockfile.
      success Saved 85 new dependencies.
      info Direct dependencies
      └─ patch-package@6.0.0-7
      info All dependencies
      ├─ ansi-align@2.0.0
      ├─ ansi-styles@3.2.1
      ├─ balanced-match@1.0.0
      ├─ boxen@1.3.0
      ├─ brace-expansion@1.1.11
      ├─ camelcase@4.1.0
      ├─ capture-stack-trace@1.0.0
      ├─ ci-info@1.1.3
      ├─ cli-boxes@1.0.0
      ├─ color-convert@1.9.2
      ├─ color-name@1.1.1
      ├─ concat-map@0.0.1
      ├─ configstore@3.1.2
      ├─ create-error-class@3.0.2
      ├─ cross-spawn@5.1.0
      ├─ crypto-random-string@1.0.0
      ├─ deep-extend@0.6.0
      ├─ dot-prop@4.2.0
      ├─ duplexer3@0.1.4
      ├─ escape-string-regexp@1.0.5
      ├─ execa@0.7.0
      ├─ fs-extra@4.0.3
      ├─ fs.realpath@1.0.0
      ├─ glob@7.1.2
      ├─ global-dirs@0.1.1
      ├─ got@6.7.1
      ├─ graceful-fs@4.1.11
      ├─ has-ansi@2.0.0
      ├─ has-flag@3.0.0
      ├─ import-lazy@2.1.0
      ├─ imurmurhash@0.1.4
      ├─ inflight@1.0.6
      ├─ inherits@2.0.3
      ├─ ini@1.3.5
      ├─ is-ci@1.1.0
      ├─ is-fullwidth-code-point@2.0.0
      ├─ is-installed-globally@0.1.0
      ├─ is-npm@1.0.0
      ├─ is-obj@1.0.1
      ├─ is-path-inside@1.0.1
      ├─ is-redirect@1.0.0
      ├─ is-retry-allowed@1.1.0
      ├─ is-stream@1.1.0
      ├─ isexe@2.0.0
      ├─ jsonfile@4.0.0
      ├─ latest-version@3.1.0
      ├─ lowercase-keys@1.0.1
      ├─ make-dir@1.3.0
      ├─ npm-run-path@2.0.2
      ├─ os-tmpdir@1.0.2
      ├─ p-finally@1.0.0
      ├─ package-json@4.0.1
      ├─ patch-package@6.0.0-7
      ├─ path-is-absolute@1.0.1
      ├─ path-is-inside@1.0.2
      ├─ path-key@2.0.1
      ├─ pify@3.0.0
      ├─ prepend-http@1.0.4
      ├─ pseudomap@1.0.2
      ├─ rc@1.2.8
      ├─ registry-auth-token@3.3.2
      ├─ registry-url@3.1.0
      ├─ rimraf@2.6.2
      ├─ semver-diff@2.1.0
      ├─ semver@5.5.0
      ├─ shebang-command@1.2.0
      ├─ shebang-regex@1.0.0
      ├─ signal-exit@3.0.2
      ├─ slash@1.0.0
      ├─ strip-ansi@3.0.1
      ├─ strip-eof@1.0.0
      ├─ strip-json-comments@2.0.1
      ├─ supports-color@5.4.0
      ├─ term-size@1.2.0
      ├─ timed-out@4.0.1
      ├─ tmp@0.0.31
      ├─ unique-string@1.0.0
      ├─ universalify@0.1.1
      ├─ unzip-response@2.0.1
      ├─ update-notifier@2.5.0
      ├─ url-parse-lax@1.0.0
      ├─ which@1.3.1
      ├─ widest-line@2.0.0
      ├─ write-file-atomic@2.3.0
      └─ yallist@2.1.2
      edit a file

      ./reverse-option.sh: line 8: replace: command not found

  ● Test reverse-option: › should exit with 0 status

    expect(received).toBe(expected)

    Expected value to be (using ===):
      0
    Received:
      127

      at Object.<anonymous> (integration-tests/runIntegrationTest.ts:28:29)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:118:7)

 FAIL  integration-tests/happy-path-yarn/happy-path-yarn.test.ts (11.129s)
  ● Console

    console.error src/spawnSafe.ts:14
      ./happy-path-yarn.sh: line 11: replace: command not found

    console.error integration-tests/runIntegrationTest.ts:26
      add patch-package
      [1/4] Resolving packages...
      [2/4] Fetching packages...
      [3/4] Linking dependencies...
      [4/4] Building fresh packages...
      success Saved lockfile.
      success Saved 1 new dependency.
      info Direct dependencies
      └─ patch-package.test.1529268562.tgz@0.0.0
      info All dependencies
      └─ patch-package.test.1529268562.tgz@0.0.0
      Add left-pad
      [1/4] Resolving packages...
      [2/4] Fetching packages...
      [3/4] Linking dependencies...
      [4/4] Building fresh packages...
      success Saved lockfile.
      success Saved 79 new dependencies.
      info Direct dependencies
      ├─ left-pad@1.1.3
      └─ patch-package.test.1529268562.tgz@6.0.0-7
      info All dependencies
      ├─ ansi-align@2.0.0
      ├─ ansi-styles@3.2.1
      ├─ boxen@1.3.0
      ├─ camelcase@4.1.0
      ├─ capture-stack-trace@1.0.0
      ├─ ci-info@1.1.3
      ├─ cli-boxes@1.0.0
      ├─ color-convert@1.9.2
      ├─ color-name@1.1.1
      ├─ configstore@3.1.2
      ├─ create-error-class@3.0.2
      ├─ cross-spawn@5.1.0
      ├─ crypto-random-string@1.0.0
      ├─ deep-extend@0.6.0
      ├─ dot-prop@4.2.0
      ├─ duplexer3@0.1.4
      ├─ escape-string-regexp@1.0.5
      ├─ execa@0.7.0
      ├─ fs-extra@4.0.3
      ├─ global-dirs@0.1.1
      ├─ got@6.7.1
      ├─ graceful-fs@4.1.11
      ├─ has-ansi@2.0.0
      ├─ has-flag@3.0.0
      ├─ import-lazy@2.1.0
      ├─ imurmurhash@0.1.4
      ├─ ini@1.3.5
      ├─ is-ci@1.1.0
      ├─ is-fullwidth-code-point@2.0.0
      ├─ is-installed-globally@0.1.0
      ├─ is-npm@1.0.0
      ├─ is-obj@1.0.1
      ├─ is-path-inside@1.0.1
      ├─ is-redirect@1.0.0
      ├─ is-retry-allowed@1.1.0
      ├─ is-stream@1.1.0
      ├─ isexe@2.0.0
      ├─ jsonfile@4.0.0
      ├─ latest-version@3.1.0
      ├─ left-pad@1.1.3
      ├─ lowercase-keys@1.0.1
      ├─ lru-cache@4.1.3
      ├─ make-dir@1.3.0
      ├─ npm-run-path@2.0.2
      ├─ os-tmpdir@1.0.2
      ├─ p-finally@1.0.0
      ├─ package-json@4.0.1
      ├─ patch-package.test.1529268562.tgz@6.0.0-7
      ├─ path-is-inside@1.0.2
      ├─ path-key@2.0.1
      ├─ pify@3.0.0
      ├─ prepend-http@1.0.4
      ├─ pseudomap@1.0.2
      ├─ rc@1.2.8
      ├─ registry-auth-token@3.3.2
      ├─ registry-url@3.1.0
      ├─ semver-diff@2.1.0
      ├─ semver@5.5.0
      ├─ shebang-command@1.2.0
      ├─ shebang-regex@1.0.0
      ├─ signal-exit@3.0.2
      ├─ slash@1.0.0
      ├─ string-width@2.1.1
      ├─ strip-ansi@3.0.1
      ├─ strip-eof@1.0.0
      ├─ strip-json-comments@2.0.1
      ├─ supports-color@5.4.0
      ├─ term-size@1.2.0
      ├─ timed-out@4.0.1
      ├─ tmp@0.0.31
      ├─ unique-string@1.0.0
      ├─ universalify@0.1.1
      ├─ unzip-response@2.0.1
      ├─ update-notifier@2.5.0
      ├─ url-parse-lax@1.0.0
      ├─ which@1.3.1
      ├─ widest-line@2.0.0
      ├─ write-file-atomic@2.3.0
      └─ yallist@2.1.2
      replace pad with yarn in left-pad/index.js

      ./happy-path-yarn.sh: line 11: replace: command not found

  ● Test happy-path-yarn: › should exit with 0 status

    expect(received).toBe(expected)

    Expected value to be (using ===):
      0
    Received:
      127

      at Object.<anonymous> (integration-tests/runIntegrationTest.ts:28:29)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:118:7)

  ● Test happy-path-yarn: › should produce some snapshots

    expect(received).toBeTruthy()

    Expected value to be truthy, instead received
      null

      at Object.<anonymous> (integration-tests/runIntegrationTest.ts:45:47)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:118:7)

 FAIL  integration-tests/happy-path-npm/happy-path-npm.test.ts (11.8s)
  ● Console

    console.error src/spawnSafe.ts:14
      npm WARN happy-path-npm@1.0.0 No repository field.

      npm WARN happy-path-npm@1.0.0 No repository field.

      npm WARN happy-path-npm@1.0.0 No repository field.

      ./happy-path-npm.sh: line 13: replace: command not found

    console.error integration-tests/runIntegrationTest.ts:26
      added 20 packages from 8 contributors and audited 27 packages in 1.776s
      found 0 vulnerabilities

      add patch-package
      + patch-package@6.0.0-7
      added 92 packages from 30 contributors and audited 27 packages in 2.719s
      found 0 vulnerabilities

      Add left-pad
      + left-pad@1.1.3
      added 1 package from 1 contributor and audited 173 packages in 3.295s
      found 0 vulnerabilities

      replace pad with yarn in left-pad/index.js

      npm WARN happy-path-npm@1.0.0 No repository field.

      npm WARN happy-path-npm@1.0.0 No repository field.

      npm WARN happy-path-npm@1.0.0 No repository field.

      ./happy-path-npm.sh: line 13: replace: command not found

  ● Test happy-path-npm: › should exit with 0 status

    expect(received).toBe(expected)

    Expected value to be (using ===):
      0
    Received:
      127

      at Object.<anonymous> (integration-tests/runIntegrationTest.ts:28:29)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:118:7)

  ● Test happy-path-npm: › should produce some snapshots

    expect(received).toBeTruthy()

    Expected value to be truthy, instead received
      null

      at Object.<anonymous> (integration-tests/runIntegrationTest.ts:45:47)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:118:7)

 PASS  integration-tests/broken-patch-file/broken-patch-file.test.ts (6.16s)
 PASS  integration-tests/shrinkwrap/shrinkwrap.test.ts (8.666s)
 PASS  integration-tests/package-gets-updated/package-gets-updated.test.ts (8.555s)
 PASS  integration-tests/adding-and-deleting-files/adding-and-deleting-files.test.ts (15.767s)

Snapshot Summary
 › 13 obsolete snapshots found, run with `yarn test -- -u` to remove them.

Test Suites: 9 failed, 4 passed, 13 total
Tests:       14 failed, 33 passed, 47 total
Snapshots:   8 passed, 8 total
Time:        20.463s
Ran all test suites matching "integration-tests".
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
 ✘  ~/Workspace/patch-package   portable-tests 

**Comment by ds300** [comment]
The tests are indeed flaky. I think it has something to do with yarn, but I never took the time to investigate properly. Normally clearing out my yarn cache will make them work again, although I noticed that the same issues were appearing on Travis for the first time recently.


`replace` should work cross-platform. It has in the past, at least. Those error messages are probably symptoms of a larger problem, rather than the cause.

**Comment by ds300** [comment]
So the issue was that I forgot that not everybody has the relative path `./node_modules/.bin` in their `$PATH`. It should be fixed now, I changed everything to run with `npx` and made the tests run in band to prevent flakiness.
