### ISSUE TITLE
404 not found error with private npm package

### ISSUE THREAD

**Issue by SamMatthewsIsACommonName** [ds300/patch-package#70]
HI!
I Really love the look of this package, but I'm running into a problem when I try and run yarn patch-package package-name: (not my private package)

````
☑ Creating temporary folder
☑ Building clean node_modules with npm
npm ERR! code E404
npm ERR! 404 Not Found: @my_npm_handle/my-package@1.5.47
````

Is this because it doesn't have the authentication needed to pull the private package in?
Thanks

**Comment by SamMatthewsIsACommonName** [comment]
Ok well pretty simple fix really, I just remove the private package to run the patch function then re install it. Hope this helps someone else who runs into this error :)

**Comment by lincolnthree** [comment]
Also having this issue, except with `npm link`ed modules. Worked around it as the OP suggested. Temporarily removed linked packages, created the patches, then added the linked packages back in. A bit of a hassle but still better than patching deps every re-install.

**Comment by ds300** [comment]
Hi! Thanks for your patience in awaiting a response.

I think there are two separate issues here.

First is the issue with private npm packages mentioned by @SamMatthewsIsACommonName – I'm not familiar with private npm authentication, is it done with `npm login`? I wonder if the way in which `npm` is invoked prevents the login credentials from being found or used. Will need to test.

Second is the issue with `npm link`ed modules. I'm not sure what the steps to reproduce would be for this. @lincolnthree do you have the modules specified in your package.json, but they are not available from the `npm` repo?

**Comment by lincolnthree** [comment]
@ds300 Thanks for the reply!

Yes, that's correct. The modules are specified in package.json, but are not available via NPM.

**Comment by ds300** [comment]
Interesting! So how are they resolved when you run `npm install`?

**Comment by lincolnthree** [comment]
@ds300 I run `npm link @my/packages` before running install. Is there a different recommendation for how to accomplish this? I'm not an expert :)

**Comment by ds300** [comment]
That's not a normal workflow, as far as I'm aware.

As for other approaches, it depends on what you're trying to achieve. Can you give some more context?

**Comment by SamMatthewsIsACommonName** [comment]
in my case yes I have to be authenticated with npm in terminal. Once do that it just pulls them in each time either with npm isntall or yarn install. Im guessing theres some more complicated things going on behind the scenes each time though!

**Comment by lincolnthree** [comment]
Ah interesting. Well... mostly I just do this because I have a package that can't be published to a public NPM repo, so I'm not sure how else to get it included in the project.

**Comment by ds300** [comment]
I'm going to close this due to inactivity. Feel free to open a new issue if you're still having trouble.
