### ISSUE TITLE
Why install as devDependency?

### ISSUE THREAD

**Issue by danilobuerger** [ds300/patch-package#74]
If we do a production install and want to patch production packages, it currently fails when following the instructions of installing patch-package as devDependency. Shouldn't the README advise people to install this as a normal dependency?

**Comment by ds300** [comment]
Hi! :wave: Apologies for the delay in getting back to you on this, I've been on holiday.

Yeah I think you're right. I come from a world where most projects have build artefacts and forget that sometimes the npm package itself is the thing that gets deployed. I think I'll change this. 👍

**Comment by ds300** [comment]
On second thoughts this feels like a niche use case and I'd rather not confuse people who might think it's ok to publish npm packages with patched dependencies.

**Comment by panva** [comment]
@ds300 i believe you're neglecting a rather important use-case. CI stack that first runs the test suite (no `npm i --production`), but in the later step prepares an artifact (not a publishable package) to push to production builds (docker images, AMIs, etc) with `npm i --production`. Or even, just plain old deployment of a verified build on a target machine where `npm i --production` is in effect.

WDYT?

**Comment by panva** [comment]
Of course this is just documentation, knowing the deployment and CI pipeline it was clear to me i must not use `--save-dev`, but it might not be clear to others who aren't aware of their production pipeline.

**Comment by ds300** [comment]
Thanks for raising this issue again. I see your point, and changed the readme to remove the --dev flag. Cheers! 👍
