### ISSUE TITLE
patch creation for @journeyapps/sqlcipher fails (6.0.0-9)

### ISSUE THREAD

**Issue by mandree** [ds300/patch-package#78]
Greetings, I am trying to create a patch against a Node.js module named @journeyapps/sqlcipher with patch-package 6.0.0-9 (or the latest 5.x.y with the same failure). Sqlcipher is a requisite to the Signal Desktop messenger as of 1.15.x.

It appears this fails horribly, the patch is generated, but it is huge, and removes most of the files:

```
 b/node_modules/@journeyapps/sqlcipher/lib/binding/electron-v2.0-linux-x64/node_sqlite3.node      |binary
 b/node_modules/@journeyapps/sqlcipher/node_modules/.bin/node-pre-gyp                             |  134 	134 +	0 -	0 !
 b/node_modules/@journeyapps/sqlcipher/package.json                                               |    7 	0 +	7 -	0 !
 node_modules/@journeyapps/sqlcipher/.gitattributes                                               |    1 	0 +	1 -	0 !
 node_modules/@journeyapps/sqlcipher/CHANGELOG.md                                                 |   14 	0 +	14 -	0 !
 node_modules/@journeyapps/sqlcipher/CONTRIBUTING.md                                              |   57 	0 +	57 -	0 !
...
```

The actual patch removes a few lines from package.json through a machine-edit to package.json with the jq tool, and that's how it looks in my shell script used to build the entire rig:

```
...
jq 'del(.binary)' node_modules/@journeyapps/sqlcipher/package.json  >.$$ && mv .$$ node_modules/@journeyapps/sqlcipher/package.json
yarn patch-package @journeyapps/sqlcipher --use-yarn --exclude "NONEXIST@"
...
```

**Comment by ds300** [comment]
Thanks for the report. I'll look into this!

**Comment by ds300** [comment]
Hi! I finally got around to looking into this, sorry for the delay! I personally can't even install `@journeyapps/sqlcipher`. The node-pre-gyp compilation fails. I'm going to close this issue due to inactivity. Feel free to open another one if you're still having trouble! :pray:
