### ISSUE TITLE
Keeping patches when updating modules to newer version

### ISSUE THREAD

**Issue by lukebrandonfarrell** [ds300/patch-package#81]
Quick question. Say I have some module. For example react-native-navigation 2.0.1, and I want to update it to 2.0.2. I run `npm update react-native-navigation`. I know that my patches to 2.0.1 will still apply to 2.0.2 as the files I patched have not been changed in 2.0.2.

How do I move my patches across? They seem to have no effect when the module has been updated.

**Comment by ds300** [comment]
Hmm oh dear that sounds like a bug. Your patches should still be applied after updating react-native-navigation, and you should also get a warning in the CLI saying that you need to explicitly mark the update as 'ok' by running `patch-package react-native-navigation` again. As a workaround you could try updating the version number in the filename of the patch file. Let me know if that works.

So I can try to reproduce this error, do you mind letting me know which versions of patch-package and git you are running and what platform you are on?

**Comment by lukebrandonfarrell** [comment]
@ds300 Alright, I don't think this is an actual issue. I was just using the tool incorrectly. Figured it out now. Thanks for the help.
