### ISSUE TITLE
Warning: Patch file found for package X which is not present...

### ISSUE THREAD

**Issue by pablopunk** [ds300/patch-package#84]
Hi, I have a repo with `patch-package` working fine but when another project has that repo as a dependency, the postinstall script tries to patch the node_modules under the first repo instead of the new one. i.e:

Here it works fine:

```
| my-lib/
--- package.json (with postinstall)
--- patches/
```

Here it doesn't:

```
| my-project/
--- package.json (with 'my-lib' as a dependency)
```

`npm install` throws: `Warning: Patch file found for package X which is not present at ~my-project/node_modules/my-lib/node_modules/X` which makes sense because it's not there, it's under `~/my-project/node_modules/X`

**Comment by gabmontes** [comment]
I have the same issue using v5.1.1.

Is it supposed to be a supported scenario? This is: install a package that has patched dependencies and a `prepare` hook in its `package.json` and have `patch-package` to apply those. It looks like if/when dependencies are deduped, `patch-package` can't find the target package to apply the patches.

**Comment by ds300** [comment]
Hi! 👋 It is not safe to publish npm packages with patched dependencies
(except devDependencies) so we don't support it.

**Comment by gabmontes** [comment]
@ds300 thanks for the clarification.

**Comment by ahammond** [comment]
We are trying to use this is for a private leaf library which needs to monkey-patched one of it's deps until we can get an upstream fix merged. Disappointing that this is blocked. :(

**Comment by jamietanna** [comment]
Has anyone found a way to work around this?

I've also got a CLI that needs to patch a dependency, and trying to find a way to apply the patch 🤔

**Comment by jamietanna** [comment]
FYI I've managed to create a workaround (which I appreciate is not best practices nor recommended) - more details to follow!

**Comment by jamietanna** [comment]
I managed to fix this by making my published module (in my case, an executable) run `patch-package` based on how the package is installed - this migrated from using `postinstall` (install time) but instead running this at runtime

(more info: https://www.jvt.me/posts/2025/04/12/patch-package-distribute/)
