### ISSUE TITLE
Is this working with lerna

### ISSUE THREAD

**Issue by belgac** [ds300/patch-package#88]
Hi,

first of all thank you for this amazing package.

I'm currently migrating one of my repos to lerna, patch-package works great for applying patches in this environment. But to create a patch, the yarn installation seems to fail because it can't find the lerna.json file. Is there an already established way to fix this?

Thanks a lot!

**Comment by ds300** [comment]
Hi! :wave:  Sorry, I haven't been able to figure out a sensible way to make patch-package work with yarn workspaces or lerna yet. It's the next major thing I want to focus on for patch package though, so stay tuned.

**Comment by ds300** [comment]
patch-package now works with yarn workspaces. I'm guessing everybody who uses lerna also uses yarn workspaces now? So I'll close this. Feel free to open a new issue specifically for lerna if there is something left to do.

See also #42

**Comment by euanmillar** [comment]
Nice one @ds300 !  I'm about to use this amazing tool again.  Hope you're well!
