### ISSUE TITLE
Using in laravel project with webpack - am I missing something?

### ISSUE THREAD

**Issue by lukio3** [ds300/patch-package#95]
Hi,

I have successfully followed the steps to create a patch. Which is in turn successfully applied (I can see the changes merged into the package in question in node_modules in my project..).

However, the changes I have made are not in my final build and do not take effect.

Is this because I am using webpack? Does anybody else use patch-package with a Laravel 5 project with laravel mix?

Many thanks

Luke

**Comment by ds300** [comment]
Sorry for the delayed response! Unfortunately, I don't know anything about laravel. Webpack works fine with patch-package though! I'm going to close this due to inactivity but feel free to reopen if you're still having trouble.
