### ISSUE TITLE
Option to Yarn use UNIX Patch instead Git

### ISSUE THREAD

**Issue by DavidUser** [ds300/patch-package#96]
I'm running yarn on container and getting the error:
```
**ERROR** patch-package requires Git
```
I really doesn't want git on container, I had see on #33 that before yarn use the UNIX patch, it's really a better option, considering that normally it's has less than 0.5MB

Had some way to opt by use UNIX patch instead git?

**Comment by ds300** [comment]
Hi! Sorry for the delayed response. `patch-package@beta` uses pure-JS patch application. You could try that (you might need to re-create the patch files after updating).
