### ISSUE TITLE
Fails to create a patch if user info is missing in global .gitconfig

### ISSUE THREAD

**Issue by sryze** [ds300/patch-package#98]
I tried to create a patch for a React Native package (react-native-sentry) for the first time using this command:

```
npx patch-package react-native-sentry
```

but it could not run because of the following errors:

```
☑ Creating temporary folder
☑ Building clean node_modules with npm
☑ Diffing your files with clean files

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident name (for <>) not allowed

{ status: 128,
  signal: null,
  output:
   [ null,
     <Buffer >,
     <Buffer 0a 2a 2a 2a 20 50 6c 65 61 73 65 20 74 65 6c 6c 20 6d 65 20 77 68 6f 20 79 6f 75 20 61 72 65 2e 0a 0a 52 75 6e 0a 0a 20 20 67 69 74 20 63 6f 6e 66 69 ... 230 more bytes> ],
  pid: 4923,
  stdout: <Buffer >,
  stderr:
   <Buffer 0a 2a 2a 2a 20 50 6c 65 61 73 65 20 74 65 6c 6c 20 6d 65 20 77 68 6f 20 79 6f 75 20 61 72 65 2e 0a 0a 52 75 6e 0a 0a 20 20 67 69 74 20 63 6f 6e 66 69 ... 230 more bytes>,
  error: null }
```

I think it's because I don't have a global user.name and user.email set in .gitconfig. I usually only set them per repository locally (git config --local) because I use different accounts for work and other stuff. 

Is it possible to create a patch without altering the global .gitconfig?

**Update:**

Yep, it's because of missing global user info. After I filled it the patch was successfully created.

**Comment by muradm** [comment]
Same here, while hard to use `global` git config.

**Comment by ds300** [comment]
Thanks for the report! :heart: I'll make it so that patch-package adds a local user and email config when it uses git.
